FuegoMain Application: FuegoMainEngine Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
FuegoMainEngine Class Reference
GTP engine for GoUctPlayer.
#include <FuegoMainEngine.h>
Public Member Functions
FuegoMainEngine (int fixedBoardSize, const char *programPath=0, bool noHandicap=false)
~FuegoMainEngine ()
void CmdAnalyzeCommands (GtpCommand &cmd)
void CmdLicense (GtpCommand &cmd)
void CmdName (GtpCommand &cmd)
void CmdVersion (GtpCommand &cmd)
Return Fuego version.
GoBook & Book ()
const GoGame & Game () const
const GoBoard & Board () const
void SetPlayer (GoPlayer *player)
GoPlayer & Player () const
void DumpState (std::ostream &out) const
void SetAutoSave (const std::string &prefix)
void SetStatisticsFile (const std::string &fileName)
void SetAutoShowBoard (bool showBoard)
void SetDebugToComment (bool debugToComment)
void SetMaxClearBoard (int n)
void SetNamedRules (const std::string &namedRules)
void SetTimeLimit (double timeLimit)
double TimeLimit ()
void SetMpiSynchronizer (const SgMpiSynchronizerHandle &m_handle)
SgMpiSynchronizerHandle MpiSynchronizer ()
const SgMpiSynchronizerHandle MpiSynchronizer () const
virtual void CmdAllLegal (GtpCommand &)
virtual void CmdAllMoveValues (GtpCommand &)
virtual void CmdBoard (GtpCommand &)
virtual void CmdBoardSize (GtpCommand &)
virtual void CmdClearBoard (GtpCommand &)
virtual void CmdClock (GtpCommand &)
virtual void CmdFinalScore (GtpCommand &)
virtual void CmdFixedHandicap (GtpCommand &)
virtual void CmdGameOver (GtpCommand &)
virtual void CmdGenMove (GtpCommand &)
virtual void CmdGenMoveCleanup (GtpCommand &)
virtual void CmdGetKomi (GtpCommand &)
virtual void CmdGGUndo (GtpCommand &)
virtual void CmdInterrupt (GtpCommand &)
virtual void CmdIsLegal (GtpCommand &)
virtual void CmdKgsTimeSettings (GtpCommand &cmd)
virtual void CmdKomi (GtpCommand &)
virtual void CmdListStones (GtpCommand &)
virtual void CmdLoadSgf (GtpCommand &)
virtual void CmdParam (GtpCommand &)
virtual void CmdParamRules (GtpCommand &)
virtual void CmdParamTimecontrol (GtpCommand &)
virtual void CmdPlaceFreeHandicap (GtpCommand &)
virtual void CmdPlay (GtpCommand &)
virtual void CmdPlayerBoard (GtpCommand &)
virtual void CmdPlaySequence (GtpCommand &)
virtual void CmdPointNumbers (GtpCommand &)
virtual void CmdPointInfo (GtpCommand &)
virtual void CmdQuit (GtpCommand &cmd)
virtual void CmdRegGenMove (GtpCommand &)
virtual void CmdRegGenMoveToPlay (GtpCommand &)
virtual void CmdRules (GtpCommand &)
virtual void CmdSaveSgf (GtpCommand &)
virtual void CmdSentinelFile (GtpCommand &)
virtual void CmdSetFreeHandicap (GtpCommand &)
virtual void CmdSetInfo (GtpCommand &)
virtual void CmdSetup (GtpCommand &)
virtual void CmdSetupPlayer (GtpCommand &)
virtual void CmdShowBoard (GtpCommand &)
virtual void CmdTimeLastMove (GtpCommand &)
virtual void CmdTimeLeft (GtpCommand &)
virtual void CmdTimeSettings (GtpCommand &)
virtual void CmdUndo (GtpCommand &)
void ExecuteFile (const std::string &name, std::ostream &log=std::cerr)
std::string ExecuteCommand (const std::string &cmd, std::ostream &log=std::cerr)
void MainLoop (GtpInputStream &in, GtpOutputStream &out)
void Register (const std::string &name, GtpCallbackBase *callback)
void Register (const std::string &command, typename GtpCallback< T >::Method method, T *instance)
bool IsRegistered (const std::string &command) const
void SetQuit ()
bool IsQuitSet () const
virtual void Ponder ()
virtual void InitPonder ()
virtual void StopPonder ()
virtual void Interrupt ()
virtual void CmdKnownCommand (GtpCommand &)
virtual void CmdListCommands (GtpCommand &)
virtual void CmdProtocolVersion (GtpCommand &)
Protected Member Functions
void BeforeHandleCommand ()
void BeforeWritingResponse ()
void BoardChanged ()
void CheckLegal (std::string message, SgBlackWhite color, SgPoint move, bool checkOnlyOccupied)
void CheckMaxClearBoard ()
void CheckMoveStackOverflow () const
SgPoint GenMove (SgBlackWhite color, bool ignoreClock)
void RespondNumberArray (GtpCommand &cmd, const SgPointArray< int > &array, int scale)
void Init (int size)
void Play (SgBlackWhite color, SgPoint move)
SgBlackWhite BlackWhiteArg (const GtpCommand &cmd, std::size_t number) const
SgEmptyBlackWhite EmptyBlackWhiteArg (const GtpCommand &cmd, std::size_t number) const
SgPoint EmptyPointArg (const GtpCommand &cmd, std::size_t number) const
SgPoint MoveArg (const GtpCommand &cmd, std::size_t number) const
SgPoint PointArg (const GtpCommand &cmd) const
SgPoint PointArg (const GtpCommand &cmd, std::size_t number) const
SgVector< SgPoint > PointListArg (const GtpCommand &cmd, std::size_t number) const
SgVector< SgPoint > PointListArg (const GtpCommand &cmd) const
SgPoint StoneArg (const GtpCommand &cmd, std::size_t number) const
void RulesChanged ()
virtual std::vector< std::string > CreateStatisticsSlots ()
virtual void AddPlayStatistics ()
void AddStatistics (const std::string &key, const std::string &value)
void AddStatistics (const std::string &key, const T &value)
Protected Attributes
GoPlayer * m_player
boost::scoped_ptr< GoAutoBook > m_autoBook
Private Types
typedef GoUctPlayer
< GoUctGlobalSearch
< GoUctPlayoutPolicy
< GoUctBoard >
, GoUctPlayoutPolicyFactory
< GoUctBoard >
>, GoUctGlobalSearchState
< GoUctPlayoutPolicy
< GoUctBoard > > > PlayerType
Private Attributes
GoUctCommands m_uctCommands
GoUctBookBuilderCommands
< PlayerType > m_autoBookCommands
GoSafetyCommands m_safetyCommands
Detailed Description
GTP engine for GoUctPlayer.
Definition at line 16 of file FuegoMainEngine.h.
Member Typedef Documentation
typedef GoUctPlayer<GoUctGlobalSearch<GoUctPlayoutPolicy<GoUctBoard>, GoUctPlayoutPolicyFactory<GoUctBoard> >, GoUctGlobalSearchState<GoUctPlayoutPolicy<GoUctBoard> > > FuegoMainEngine::PlayerType [private]
Definition at line 36 of file FuegoMainEngine.h.
Constructor & Destructor Documentation
FuegoMainEngine::FuegoMainEngine (int fixedBoardSize, const char * programPath = 0, bool noHandicap = false)
Definition at line 17 of file FuegoMainEngine.cpp.
References GoGtpEngine::Board(), CmdLicense(), m_autoBookCommands, m_safetyCommands, m_uctCommands, GtpEngine::Register(), GoUctBookBuilderCommands< class >::Register(), GoSafetyCommands::Register(), GoUctCommands::Register(), and GoGtpEngine::SetPlayer().
FuegoMainEngine::~FuegoMainEngine ()
Definition at line 31 of file FuegoMainEngine.cpp.
Member Function Documentation
void FuegoMainEngine::CmdAnalyzeCommands (GtpCommand & cmd) [virtual]
Reimplemented from GoGtpEngine.
Definition at line 35 of file FuegoMainEngine.cpp.
References GoUctBookBuilderCommands< class >::AddGoGuiAnalyzeCommands(), GoSafetyCommands::AddGoGuiAnalyzeCommands(), GoUctCommands::AddGoGuiAnalyzeCommands(), m_autoBookCommands, m_safetyCommands, m_uctCommands, GtpCommand::Response(), GtpCommand::SetResponse(), and GoGtpCommandUtil::SortResponseAnalyzeCommands().
void FuegoMainEngine::CmdLicense (GtpCommand & cmd)
Definition at line 46 of file FuegoMainEngine.cpp.
References FuegoMainUtil::Version().
Referenced by FuegoMainEngine().
void FuegoMainEngine::CmdName (GtpCommand & cmd) [virtual]
Reimplemented from GoGtpEngine.
Definition at line 59 of file FuegoMainEngine.cpp.
void FuegoMainEngine::CmdVersion (GtpCommand & cmd) [virtual]
Return Fuego version.
See also:
FuegoMainUtil::Version()
Reimplemented from GtpEngine.
Definition at line 66 of file FuegoMainEngine.cpp.
References FuegoMainUtil::Version().
Member Data Documentation
GoUctBookBuilderCommands<PlayerType> FuegoMainEngine::m_autoBookCommands [private]
Definition at line 38 of file FuegoMainEngine.h.
Referenced by CmdAnalyzeCommands(), and FuegoMainEngine().
GoSafetyCommands FuegoMainEngine::m_safetyCommands [private]
Definition at line 40 of file FuegoMainEngine.h.
Referenced by CmdAnalyzeCommands(), and FuegoMainEngine().
GoUctCommands FuegoMainEngine::m_uctCommands [private]
Definition at line 31 of file FuegoMainEngine.h.
Referenced by CmdAnalyzeCommands(), and FuegoMainEngine().
The documentation for this class was generated from the following files:
FuegoMainEngine.h
FuegoMainEngine.cpp
Sun Mar 13 2011 Doxygen 1.7.1