FuegoMain Application: FuegoMain.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
FuegoMain.cpp File Reference
Main function for Fuego.
#include "SgSystem.h"
#include <iostream>
#include <boost/foreach.hpp>
#include <boost/format.hpp>
#include <boost/filesystem/path.hpp>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/cmdline.hpp>
#include <boost/program_options/variables_map.hpp>
#include <boost/program_options/parsers.hpp>
#include <boost/utility.hpp>
#include "FuegoMainEngine.h"
#include "FuegoMainUtil.h"
#include "GoInit.h"
#include "SgDebug.h"
#include "SgException.h"
#include "SgInit.h"
Functions
int main (int argc, char **argv)
Detailed Description
Main function for Fuego.
Definition in file FuegoMain.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 137 of file FuegoMain.cpp.
References GoGtpEngine::Book(), GtpEngine::ExecuteFile(), GoInit(), FuegoMainUtil::LoadBook(), GtpEngine::MainLoop(), GtpFailure::Response(), GoGtpEngine::SetMaxClearBoard(), SgRandom::SetSeed(), SgDebug(), SgDebugToNull(), SgInit(), and SgException::what().
Sun Mar 13 2011 Doxygen 1.7.1