FuegoMain Application: FuegoMainUtil Namespace Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
FuegoMainUtil Namespace Reference
Functions
void LoadBook (GoBook &book, const boost::filesystem::path &programDir)
Try to load opening book from a set of known paths.
std::string Version ()
Return Fuego version.
Function Documentation
void FuegoMainUtil::LoadBook (GoBook & book, const boost::filesystem::path & programDir)
Try to load opening book from a set of known paths.
The file name is "book.dat". The paths tried are (in this order):
the directory of the executable
ABS_TOP_SRCDIR/book
DATADIR/PACKAGE
Parameters:
book The opening book to load
programDir the directory of the executable (may be a relative path or an empty string)
Exceptions:
SgException,if book is not found
Definition at line 50 of file FuegoMainUtil.cpp.
Referenced by main().
std::string FuegoMainUtil::Version ()
Return Fuego version.
If the macro VERSION was defined by the build system during compile time, its value is used as the version, otherwise the version is "(__DATE__)". If SVNREV is defined, (SVNREV) is added. If compiled in debug mode, " (dbg)" is added.
Definition at line 67 of file FuegoMainUtil.cpp.
Referenced by FuegoMainEngine::CmdLicense(), and FuegoMainEngine::CmdVersion().
Sun Mar 13 2011 Doxygen 1.7.1