Go Library: GoPlayerMove Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoPlayerMove Class Reference
Move and color of player who plays it.
#include <GoPlayerMove.h>
Public Member Functions
GoPlayerMove (SgBlackWhite color, SgPoint point=SG_NULLMOVE)
GoPlayerMove ()
~GoPlayerMove ()
bool operator== (const GoPlayerMove &move) const
bool operator!= (const GoPlayerMove &move) const
SgPoint Point () const
SgBlackWhite Color () const
void SetPoint (SgPoint move)
Private Attributes
SgBlackWhite m_color
SgPoint m_point
Detailed Description
Move and color of player who plays it.
Definition at line 15 of file GoPlayerMove.h.
Constructor & Destructor Documentation
GoPlayerMove::GoPlayerMove (SgBlackWhite color, SgPoint point = SG_NULLMOVE)
Definition at line 46 of file GoPlayerMove.h.
References SG_ASSERT_BW.
GoPlayerMove::GoPlayerMove ()
Definition at line 40 of file GoPlayerMove.h.
References SG_BLACK, and SG_NULLMOVE.
GoPlayerMove::~GoPlayerMove ()
Definition at line 53 of file GoPlayerMove.h.
Member Function Documentation
SgBlackWhite GoPlayerMove::Color () const
Definition at line 77 of file GoPlayerMove.h.
References m_color.
Referenced by GoBoardUtil::DumpBoard(), GoBoardHistory::IsAlternatePlayFollowUpOf(), GoRegionBoard::OnExecutedMove(), operator<<(), and GoBoard::Play().
bool GoPlayerMove::operator!= (const GoPlayerMove & move) const
Definition at line 62 of file GoPlayerMove.h.
References operator==().
bool GoPlayerMove::operator== (const GoPlayerMove & move) const
Definition at line 57 of file GoPlayerMove.h.
References m_color, and m_point.
Referenced by operator!=().
SgPoint GoPlayerMove::Point () const
Definition at line 67 of file GoPlayerMove.h.
References m_point.
Referenced by GoBoardUtil::DumpBoard(), GoAutoBook::ExportToOldFormat(), GoBoardHistory::IsAlternatePlayFollowUpOf(), GoRegionBoard::OnExecutedMove(), operator<<(), GoBoard::Play(), and GoAutoBookState::Synchronize().
void GoPlayerMove::SetPoint (SgPoint move)
Definition at line 72 of file GoPlayerMove.h.
References m_point.
Member Data Documentation
SgBlackWhite GoPlayerMove::m_color [private]
Definition at line 35 of file GoPlayerMove.h.
Referenced by Color(), and operator==().
SgPoint GoPlayerMove::m_point [private]
Definition at line 37 of file GoPlayerMove.h.
Referenced by operator==(), Point(), and SetPoint().
The documentation for this class was generated from the following file:
GoPlayerMove.h
Sun Mar 13 2011 Doxygen 1.7.1