Go Library: GoSortedMoves Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoSortedMoves Class Reference
Specialization of SgSortedMoves for Go: move = SgMove, value = int.
#include <GoSortedMoves.h>
Public Member Functions
GoSortedMoves (int maxNuMoves)
GoSortedMoves ()
void Clear ()
void CheckOverflow ()
void DeleteEqual ()
void Delete (int index)
void Insert (const SgMove &move, intvalue)
bool GetMove (const SgMove &move, int &value, int &index) const
void GetMoves (SgVector< SgMove > *moves) const
void SetMinValue (const SgMove &move, intvalue)
void SetMove (int i, const SgMove &move)
void SetValue (int i, intvalue)
void SetMaxMoves (int nu)
void SetMaxNuMoves (int max)
void SetLowerBound (intbound)
void SetInitLowerBound (intbound)
int LowerBound () const
int NuMoves () const
int MaxNuMoves () const
const SgMove & Move (int i) const
const SgMove & BestMove () const
int Value (int i) const
int BestValue () const
void DecNuMoves ()
void AssertIndexRange (int i) const
void Shuffle ()
Static Public Attributes
static const bool CHECKMOVES
Detailed Description
Specialization of SgSortedMoves for Go: move = SgMove, value = int.
Todo:
make maxNuMoves a template parameter, use instead of GO_SORTED_MOVES_MAX
Definition at line 20 of file GoSortedMoves.h.
Constructor & Destructor Documentation
GoSortedMoves::GoSortedMoves (int maxNuMoves) [explicit]
Definition at line 24 of file GoSortedMoves.h.
References Clear().
GoSortedMoves::GoSortedMoves ()
Definition at line 30 of file GoSortedMoves.h.
References Clear().
Member Function Documentation
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::AssertIndexRange (int i) const [inherited]
const SgMove & SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::BestMove () const [inherited]
int SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::BestValue () const [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::CheckOverflow () [inherited]
void GoSortedMoves::Clear ()
Reimplemented from SgSortedMoves< SgMove, int, GO_SORTED_MOVES_MAX >.
Definition at line 37 of file GoSortedMoves.h.
References SgSortedMoves< SgMove, int, GO_SORTED_MOVES_MAX >::SetInitLowerBound(), and SgSortedMoves< SgMove, int, GO_SORTED_MOVES_MAX >::SetLowerBound().
Referenced by GoSortedMoves().
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::DecNuMoves () [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::Delete (int index) [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::DeleteEqual () [inherited]
bool SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::GetMove (const SgMove & move, int & value, int & index) const [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::GetMoves (SgVector< SgMove > * moves) const [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::Insert (const SgMove & move, int value) [inherited]
int SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::LowerBound () const [inherited]
int SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::MaxNuMoves () const [inherited]
const SgMove & SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::Move (int i) const [inherited]
int SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::NuMoves () const [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::SetInitLowerBound (int bound) [inherited]
Referenced by Clear().
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::SetLowerBound (int bound) [inherited]
Referenced by Clear().
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::SetMaxMoves (int nu) [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::SetMaxNuMoves (int max) [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::SetMinValue (const SgMove & move, int value) [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::SetMove (int i, const SgMove & move) [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::SetValue (int i, int value) [inherited]
void SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::Shuffle () [inherited]
int SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::Value (int i) const [inherited]
Member Data Documentation
const bool SgSortedMoves< SgMove , int , GO_SORTED_MOVES_MAX >::CHECKMOVES [static, inherited]
The documentation for this class was generated from the following file:
GoSortedMoves.h
Sun Mar 13 2011 Doxygen 1.7.1