Go Library: GoBoardRestorer Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoBoardRestorer Class Reference
Remembers the state of a board and restores it in its destructor.
#include <GoBoardRestorer.h>
Public Member Functions
GoBoardRestorer (GoBoard &bd)
~GoBoardRestorer ()
Private Types
typedef SgArrayList
< GoPlayerMove,
GO_MAX_NUM_MOVES > MoveList
Private Attributes
GoBoard & m_bd
int m_size
GoRules m_rules
MoveList m_moves
Detailed Description
Remembers the state of a board and restores it in its destructor.
Definition at line 13 of file GoBoardRestorer.h.
Member Typedef Documentation
typedef SgArrayList<GoPlayerMove,GO_MAX_NUM_MOVES> GoBoardRestorer::MoveList [private]
Definition at line 21 of file GoBoardRestorer.h.
Constructor & Destructor Documentation
GoBoardRestorer::GoBoardRestorer (GoBoard & bd)
Definition at line 15 of file GoBoardRestorer.cpp.
References m_moves, GoBoard::Move(), GoBoard::MoveNumber(), and SgArrayList< T, SIZE >::PushBack().
GoBoardRestorer::~GoBoardRestorer ()
Definition at line 24 of file GoBoardRestorer.cpp.
References GoBoard::Init(), SgArrayList< GoPlayerMove, GO_MAX_NUM_MOVES >::Iterator, m_bd, m_moves, m_size, GoBoard::Play(), GoBoard::Size(), and GoBoardUtil::UndoAll().
Member Data Documentation
GoBoard& GoBoardRestorer::m_bd [private]
Definition at line 23 of file GoBoardRestorer.h.
Referenced by ~GoBoardRestorer().
MoveList GoBoardRestorer::m_moves [private]
Definition at line 29 of file GoBoardRestorer.h.
Referenced by GoBoardRestorer(), and ~GoBoardRestorer().
GoRules GoBoardRestorer::m_rules [private]
Definition at line 27 of file GoBoardRestorer.h.
int GoBoardRestorer::m_size [private]
Definition at line 25 of file GoBoardRestorer.h.
Referenced by ~GoBoardRestorer().
The documentation for this class was generated from the following files:
GoBoardRestorer.h
GoBoardRestorer.cpp
Sun Mar 13 2011 Doxygen 1.7.1