Go Library: GoBoardHistory Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoBoardHistory Class Reference
Identifier for board state including history.
#include <GoBoardHistory.h>
Public Member Functions
GoBoardHistory ()
Constructor.
void SetFromBoard (const GoBoard &bd)
Initialize from a current board position.
bool IsAlternatePlayFollowUpOf (const GoBoardHistory &other, std::vector< SgPoint > &sequence)
Check if this position is a alternate-play follow-up to another one.
Private Attributes
int m_boardSize
GoRules m_rules
GoSetup m_setup
SgArrayList< GoPlayerMove,
GO_MAX_NUM_MOVES > m_moves
SgBlackWhite m_toPlay
Detailed Description
Identifier for board state including history.
This class can be used, for instance, to uniquely remember a board position for reusing parts of previous computations. The state includes:
the board size
the rules
the setup stones and color to play before any moves were played
the history of moves (needed if super-ko rules are used)
the current color to play
Definition at line 21 of file GoBoardHistory.h.
Constructor & Destructor Documentation
GoBoardHistory::GoBoardHistory ()
Constructor.
The initial state is that the history does not correspond to any valid position.
Definition at line 52 of file GoBoardHistory.h.
Member Function Documentation
bool GoBoardHistory::IsAlternatePlayFollowUpOf (const GoBoardHistory & other, std::vector< SgPoint > & sequence)
Check if this position is a alternate-play follow-up to another one.
Parameters:
other The other position
[out] sequence The sequence leading from the other position to this one
Returns:
true If the position is a follow-up
Definition at line 24 of file GoBoardHistory.cpp.
References GoPlayerMove::Color(), SgArrayList< T, SIZE >::Length(), m_boardSize, m_moves, m_rules, m_setup, m_toPlay, GoPlayerMove::Point(), and SgOppBW().
void GoBoardHistory::SetFromBoard (const GoBoard & bd)
Initialize from a current board position.
Definition at line 13 of file GoBoardHistory.cpp.
References SgArrayList< T, SIZE >::Clear(), m_boardSize, m_moves, m_rules, m_setup, m_toPlay, GoBoard::Move(), GoBoard::MoveNumber(), SgArrayList< T, SIZE >::PushBack(), GoBoard::Rules(), GoBoard::Setup(), GoBoard::Size(), and GoBoard::ToPlay().
Member Data Documentation
int GoBoardHistory::m_boardSize [private]
Definition at line 41 of file GoBoardHistory.h.
Referenced by IsAlternatePlayFollowUpOf(), and SetFromBoard().
SgArrayList<GoPlayerMove,GO_MAX_NUM_MOVES> GoBoardHistory::m_moves [private]
Definition at line 47 of file GoBoardHistory.h.
Referenced by IsAlternatePlayFollowUpOf(), and SetFromBoard().
GoRules GoBoardHistory::m_rules [private]
Definition at line 43 of file GoBoardHistory.h.
Referenced by IsAlternatePlayFollowUpOf(), and SetFromBoard().
GoSetup GoBoardHistory::m_setup [private]
Definition at line 45 of file GoBoardHistory.h.
Referenced by IsAlternatePlayFollowUpOf(), and SetFromBoard().
SgBlackWhite GoBoardHistory::m_toPlay [private]
Definition at line 49 of file GoBoardHistory.h.
Referenced by IsAlternatePlayFollowUpOf(), and SetFromBoard().
The documentation for this class was generated from the following files:
GoBoardHistory.h
GoBoardHistory.cpp
Sun Mar 13 2011 Doxygen 1.7.1