Go Library: GoBook::Entry Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoBook::Entry Class Reference
#include <GoBook.h>
Public Member Functions
void ApplyTo (GoBoard &bd) const
Setup entry on a board.
Public Attributes
int m_size
Board size.
int m_line
Line number in the original file.
std::vector< SgPoint > m_sequence
std::vector< SgPoint > m_moves
Detailed Description
Definition at line 42 of file GoBook.h.
Member Function Documentation
void GoBook::Entry::ApplyTo (GoBoard & bd) const
Setup entry on a board.
Definition at line 66 of file GoBook.cpp.
References GoBoard::Init(), GoBoard::IsLegal(), m_sequence, m_size, GoBoard::Play(), SG_ASSERT, GoBoard::Size(), and GoBoardUtil::UndoAll().
Member Data Documentation
int GoBook::Entry::m_line
Line number in the original file.
Definition at line 49 of file GoBook.h.
Referenced by GoBook::InsertEntry().
std::vector<SgPoint> GoBook::Entry::m_moves
Definition at line 53 of file GoBook.h.
Referenced by GoBook::InsertEntry().
std::vector<SgPoint> GoBook::Entry::m_sequence
Definition at line 51 of file GoBook.h.
Referenced by ApplyTo(), and GoBook::InsertEntry().
int GoBook::Entry::m_size
Board size.
Definition at line 46 of file GoBook.h.
Referenced by ApplyTo(), and GoBook::InsertEntry().
The documentation for this class was generated from the following files:
GoBook.h
GoBook.cpp
Sun Mar 13 2011 Doxygen 1.7.1