Go Library: GoBoardUtil.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoBoardUtil.cpp File Reference
See GoBoardUtil.h.
#include "SgSystem.h"
#include "GoBoardUtil.h"
#include <iomanip>
#include <sstream>
#include <string>
#include "GoBoard.h"
#include "GoModBoard.h"
#include "GoMoveExecutor.h"
#include "GoSafetySolver.h"
#include "SgDebug.h"
#include "SgException.h"
#include "SgNbIterator.h"
#include "SgProp.h"
Functions
std::ostream & operator<< (std::ostream &out, const GoBoardWrite::WriteMap &w)
Detailed Description
See GoBoardUtil.h.
Definition in file GoBoardUtil.cpp.
Function Documentation
std::ostream& operator<< (std::ostream & out, const GoBoardWrite::WriteMap & w)
Definition at line 966 of file GoBoardUtil.cpp.
References GoBoardWrite::WriteMap::Board(), GoBoardWrite::WriteMap::Points(), GoBoard::Size(), and SgPointSet::Write().
Sun Mar 13 2011 Doxygen 1.7.1