Go Library: GoChain.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoChain.h File Reference
A chain contained in a.
#include <iosfwd>
#include "GoBlock.h"
#include "GoBoard.h"
#include "SgBlackWhite.h"
#include "SgPoint.h"
#include "SgVector.h"
Classes
class GoChainCondition
Condition that explains why two blocks or chains can be merged into a new, larger chain.
class GoChain
Set of GoBlock's that are a connected unit.
Enumerations
enum GoChainType { GO_CHAIN_TWO_LIBERTIES_IN_REGION, GO_CHAIN_TWO_SEPARATE_LIBERTIES, GO_CHAIN_BY_SEARCH, _GO_CHAIN_COUNT }
The reason why two blocks or chains are merged into a single chain.
Functions
std::ostream & operator<< (std::ostream &stream, GoChainType f)
std::ostream & operator<< (std::ostream &stream, const GoChainCondition &c)
std::ostream & operator<< (std::ostream &stream, const GoChain &c)
Detailed Description
A chain contained in a.
See also:
GoRegionBoard.
Definition in file GoChain.h.
Enumeration Type Documentation
enum GoChainType
The reason why two blocks or chains are merged into a single chain.
Enumerator:
GO_CHAIN_TWO_LIBERTIES_IN_REGION
GO_CHAIN_TWO_SEPARATE_LIBERTIES
GO_CHAIN_BY_SEARCH
_GO_CHAIN_COUNT
Definition at line 23 of file GoChain.h.
Function Documentation
std::ostream& operator<< (std::ostream & stream, GoChainType f)
Definition at line 143 of file GoChain.cpp.
std::ostream& operator<< (std::ostream & stream, const GoChain & c)
Definition at line 111 of file GoChain.cpp.
References GoChain::Write().
std::ostream& operator<< (std::ostream & stream, const GoChainCondition & c)
Definition at line 158 of file GoChain.cpp.
References GoChainCondition::Lib1(), GoChainCondition::Lib2(), GoChainCondition::Type(), and GoChainCondition::UsesLibs().
Sun Mar 13 2011 Doxygen 1.7.1