Go Library: GoEyeCount.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoEyeCount.h File Reference
Upper and lower bounds on number of eyes and potential eyes.
#include <ostream>
Classes
class GoEyeCount
upper and lower bounds on number of eyes and potential eyes
Enumerations
enum GoEyeStatus {
EYE_UNKNOWN, EYE_NONE, EYE_HALF, EYE_ONE,
EYE_ONE_AND_HALF, EYE_TWO
}
Quick summary of eye status.
Functions
std::ostream & operator<< (std::ostream &stream, const GoEyeCount &s)
Detailed Description
Upper and lower bounds on number of eyes and potential eyes.
Also track whether an area can form a local seki.
Todo:
the implementation of seki support is incomplete.
needs unit test cases.
Definition in file GoEyeCount.h.
Enumeration Type Documentation
enum GoEyeStatus
Quick summary of eye status.
Todo:
there are more cases, see Landman's paper in Games of no Chance.
Will add them later as needed.
Enumerator:
EYE_UNKNOWN
EYE_NONE
EYE_HALF
EYE_ONE
EYE_ONE_AND_HALF
EYE_TWO
Definition at line 21 of file GoEyeCount.h.
Function Documentation
std::ostream& operator<< (std::ostream & stream, const GoEyeCount & s)
Definition at line 67 of file GoEyeCount.cpp.
References GoEyeCount::IsLocalSeki(), GoEyeCount::MaxEyes(), GoEyeCount::MaxPotEyes(), GoEyeCount::MaybeLocalSeki(), GoEyeCount::MinEyes(), and GoEyeCount::MinPotEyes().
Sun Mar 13 2011 Doxygen 1.7.1