Go Library: GoEyeCount.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoEyeCount.cpp File Reference
See GoEyeCount.h.
#include "SgSystem.h"
#include "GoEyeCount.h"
#include <algorithm>
#include "SgWrite.h"
Functions
std::ostream & operator<< (std::ostream &stream, const GoEyeCount &s)
Detailed Description
See GoEyeCount.h.
Definition in file GoEyeCount.cpp.
Function Documentation
std::ostream& operator<< (std::ostream & stream, const GoEyeCount & s)
Definition at line 67 of file GoEyeCount.cpp.
References GoEyeCount::IsLocalSeki(), GoEyeCount::MaxEyes(), GoEyeCount::MaxPotEyes(), GoEyeCount::MaybeLocalSeki(), GoEyeCount::MinEyes(), and GoEyeCount::MinPotEyes().
Sun Mar 13 2011 Doxygen 1.7.1