Go Library: GoInit.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoInit.cpp File Reference
#include "SgSystem.h"
#include "GoInit.h"
#include "GoRegion.h"
#include "SgException.h"
#include "SgInit.h"
#include "SgProp.h"
Functions
void GoFini ()
void GoInit ()
Initialization of module Go.
void GoInitCheck ()
Detailed Description
Definition in file GoInit.cpp.
Function Documentation
void GoFini ()
Definition at line 35 of file GoInit.cpp.
References GoRegion::Fini().
void GoInit ()
Initialization of module Go.
Must be called after SgInit.
Exceptions:
SgException on failure.
Definition at line 41 of file GoInit.cpp.
References SgInitCheck().
void GoInitCheck ()
Definition at line 48 of file GoInit.cpp.
Referenced by GoBoard::GoBoard(), and GoGame::GoGame().
Sun Mar 13 2011 Doxygen 1.7.1