Go Library: GoInfluence Namespace Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoInfluence Namespace Reference
Functions
void FindInfluence (const GoBoard &board, int nuExpand, int nuShrink, SgBWSet *result)
Compute influence by nuExpand expansions followed by nuShrink contractions.
int Influence (const GoBoard &board, SgBlackWhite color, int nuExpand, int nuShrink)
Influence of a single player.
void ComputeInfluence (const GoBoard &board, const SgBWSet &stopPts, SgBWArray< SgPointArray< int > > *influence)
Compute influence, stopping at stopPts.
Function Documentation
void GoInfluence::ComputeInfluence (const GoBoard & board, const SgBWSet & stopPts, SgBWArray< SgPointArray< int > > * influence)
Compute influence, stopping at stopPts.
Definition at line 70 of file GoInfluence.cpp.
References GoBoard::IsColor().
void GoInfluence::FindInfluence (const GoBoard & board, int nuExpand, int nuShrink, SgBWSet * result)
Compute influence by nuExpand expansions followed by nuShrink contractions.
Starts from the player's stones. Expand: add the neighbor points Shrink: take away the points on the border of the set
Definition at line 31 of file GoInfluence.cpp.
References GoBoard::All(), SG_BLACK, SG_WHITE, SgOppBW(), and GoBoard::Size().
Referenced by Influence().
int GoInfluence::Influence (const GoBoard & board, SgBlackWhite color, int nuExpand, int nuShrink)
Influence of a single player.
See also:
FindInfluence. If possible use FindInfluence directly instead of calling this twice for black and white.
Definition at line 59 of file GoInfluence.cpp.
References FindInfluence().
Sun Mar 13 2011 Doxygen 1.7.1