SmartGame Library: SgPointUtil::PointToRow Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgPointUtil::PointToRow Class Reference
Lookup table internally used by SgPointUtil::Row().
#include <SgPoint.h>
Public Member Functions
PointToRow ()
SgGrid Row (SgPoint p) const
Private Attributes
SgArray< SgGrid, SG_MAXPOINT > m_row
Detailed Description
Lookup table internally used by SgPointUtil::Row().
Definition at line 225 of file SgPoint.h.
Constructor & Destructor Documentation
SgPointUtil::PointToRow::PointToRow ()
Definition at line 228 of file SgPoint.h.
References SgArray< T, SIZE >::Fill(), m_row, SgPointUtil::Pt(), and SG_MAX_SIZE.
Member Function Documentation
SgGrid SgPointUtil::PointToRow::Row (SgPoint p) const
Definition at line 236 of file SgPoint.h.
References m_row, SG_ASSERT, and SG_ASSERT_BOARDRANGE.
Referenced by SgPointUtil::Row().
Member Data Documentation
SgArray<SgGrid,SG_MAXPOINT> SgPointUtil::PointToRow::m_row [private]
Definition at line 244 of file SgPoint.h.
Referenced by PointToRow(), and Row().
The documentation for this class was generated from the following file:
SgPoint.h
Sun Mar 13 2011 Doxygen 1.7.1