SmartGame Library: SgReadPoint Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgReadPoint Class Reference
Read point.
#include <SgPoint.h>
Public Member Functions
SgReadPoint (SgPoint &point)
void Read (std::istream &in) const
Private Attributes
SgPoint & m_point
Related Functions
(Note that these are not member functions.)
std::istream & operator>> (std::istream &in, const SgReadPoint &readPoint)
Detailed Description
Read point.
For overloading input stream operator for SgPoint (which is an integer). Usage:
    istream& in;
    SgPoint point;
    in >> SgReadPoint(point);
    if (! in)
       SgDebug() << "Invalid point\n";
Definition at line 186 of file SgPoint.h.
Constructor & Destructor Documentation
SgReadPoint::SgReadPoint (SgPoint & point)
Definition at line 197 of file SgPoint.h.
Member Function Documentation
void SgReadPoint::Read (std::istream & in) const
Definition at line 94 of file SgPoint.cpp.
References SgUtil::InRange(), m_point, SgPointUtil::Pt(), SG_ASSERT, SG_COUPONMOVE, SG_COUPONMOVE_VIRTUAL, SG_MAX_SIZE, SG_PASS, and SG_RESIGN.
Referenced by operator>>().
Friends And Related Function Documentation
std::istream & operator>> (std::istream & in, const SgReadPoint & readPoint) [related]
Definition at line 203 of file SgPoint.h.
Member Data Documentation
SgPoint& SgReadPoint::m_point [private]
Definition at line 194 of file SgPoint.h.
Referenced by Read().
The documentation for this class was generated from the following files:
SgPoint.h
SgPoint.cpp
Sun Mar 13 2011 Doxygen 1.7.1