SmartGame Library: SgNodeSearchControl Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgNodeSearchControl Class Reference
Example of a simple search abort class: abort when node limit is reached.
#include <SgSearchControl.h>
Public Member Functions
SgNodeSearchControl (int maxNumNodes)
virtual ~SgNodeSearchControl ()
virtual bool Abort (double ignoreElapsedTime, int numNodes)
Check if search should be aborted.
void SetMaxNumNodes (int maxNumNodes)
virtual bool StartNextIteration (int depth, double elapsedTime, int numNodes)
Check if next iteration should be started.
Private Member Functions
SgNodeSearchControl (const SgNodeSearchControl &)
Not implemented.
SgNodeSearchControl & operator= (const SgNodeSearchControl &)
Not implemented.
Private Attributes
int m_maxNumNodes
Detailed Description
Example of a simple search abort class: abort when node limit is reached.
Definition at line 89 of file SgSearchControl.h.
Constructor & Destructor Documentation
SgNodeSearchControl::SgNodeSearchControl (int maxNumNodes)
Definition at line 43 of file SgSearchControl.cpp.
SgNodeSearchControl::~SgNodeSearchControl () [virtual]
Definition at line 47 of file SgSearchControl.cpp.
SgNodeSearchControl::SgNodeSearchControl (const SgNodeSearchControl &) [private]
Not implemented.
Member Function Documentation
bool SgNodeSearchControl::Abort (double elapsedTime, int numNodes) [virtual]
Check if search should be aborted.
Called at each node.
Implements SgSearchControl.
Definition at line 51 of file SgSearchControl.cpp.
References m_maxNumNodes, and SG_UNUSED().
SgNodeSearchControl& SgNodeSearchControl::operator= (const SgNodeSearchControl &) [private]
Not implemented.
void SgNodeSearchControl::SetMaxNumNodes (int maxNumNodes)
Definition at line 111 of file SgSearchControl.h.
References m_maxNumNodes.
bool SgSearchControl::StartNextIteration (int depth, double elapsedTime, int numNodes) [virtual, inherited]
Check if next iteration should be started.
Called before each iteration. The default implementation always returns true.
Parameters:
depth The depth of the next iteration.
elapsedTime The elapsed time in seconds.
numNodes The number of nodes visited.
Definition at line 15 of file SgSearchControl.cpp.
References SG_UNUSED().
Referenced by SgSearch::IteratedSearch().
Member Data Documentation
int SgNodeSearchControl::m_maxNumNodes [private]
Definition at line 102 of file SgSearchControl.h.
Referenced by Abort(), and SetMaxNumNodes().
The documentation for this class was generated from the following files:
SgSearchControl.h
SgSearchControl.cpp
Sun Mar 13 2011 Doxygen 1.7.1