SmartGame Library: SgStatisticsExt< VALUE, COUNT > Class Template Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgStatisticsExt< VALUE, COUNT > Class Template Reference
Extended version of SgStatistics.
#include <SgStatistics.h>
Public Member Functions
SgStatisticsExt ()
void Add (VALUE val)
void Clear ()
bool IsDefined () const
VALUE Mean () const
COUNT Count () const
VALUE Max () const
VALUE Min () const
VALUE Deviation () const
VALUE Variance () const
void Write (std::ostream &out) const
Private Attributes
SgStatistics< VALUE, COUNT > m_statistics
VALUE m_max
VALUE m_min
Detailed Description
template<typename VALUE, typename COUNT>
class SgStatisticsExt< VALUE, COUNT >
Extended version of SgStatistics.
Also stores minimum and maximum values. The template parameters are the floating point type and the counter type, depending on the precision-memory tradeoff.
Definition at line 373 of file SgStatistics.h.
Constructor & Destructor Documentation
template<typename VALUE , typename COUNT > SgStatisticsExt< VALUE, COUNT >::SgStatisticsExt ()
Definition at line 407 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::Clear().
Member Function Documentation
template<typename VALUE, typename COUNT > void SgStatisticsExt< VALUE, COUNT >::Add (VALUE val)
Definition at line 413 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_max, SgStatisticsExt< VALUE, COUNT >::m_min, and SgStatisticsExt< VALUE, COUNT >::m_statistics.
Referenced by SgUctTreeStatistics::Compute(), and SgUctSearch::UpdateStatistics().
template<typename VALUE , typename COUNT > void SgStatisticsExt< VALUE, COUNT >::Clear ()
Definition at line 423 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_max, SgStatisticsExt< VALUE, COUNT >::m_min, and SgStatisticsExt< VALUE, COUNT >::m_statistics.
Referenced by SgUctTreeStatistics::Clear(), SgUctSearchStat::Clear(), and SgStatisticsExt< VALUE, COUNT >::SgStatisticsExt().
template<typename VALUE , typename COUNT > COUNT SgStatisticsExt< VALUE, COUNT >::Count () const
Definition at line 431 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_statistics.
template<typename VALUE , typename COUNT > VALUE SgStatisticsExt< VALUE, COUNT >::Deviation () const
Definition at line 437 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_statistics.
template<typename VALUE , typename COUNT > bool SgStatisticsExt< VALUE, COUNT >::IsDefined () const
Definition at line 443 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_statistics.
Referenced by SgStatisticsExt< VALUE, COUNT >::Write().
template<typename VALUE , typename COUNT > VALUE SgStatisticsExt< VALUE, COUNT >::Max () const
Definition at line 449 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_max.
template<typename VALUE , typename COUNT > VALUE SgStatisticsExt< VALUE, COUNT >::Mean () const
Definition at line 455 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_statistics.
template<typename VALUE , typename COUNT > VALUE SgStatisticsExt< VALUE, COUNT >::Min () const
Definition at line 461 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_min.
template<typename VALUE , typename COUNT > VALUE SgStatisticsExt< VALUE, COUNT >::Variance () const
Definition at line 467 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::m_statistics.
template<typename VALUE , typename COUNT > void SgStatisticsExt< VALUE, COUNT >::Write (std::ostream & out) const
Definition at line 473 of file SgStatistics.h.
References SgStatisticsExt< VALUE, COUNT >::IsDefined(), SgStatisticsExt< VALUE, COUNT >::m_max, SgStatisticsExt< VALUE, COUNT >::m_min, and SgStatisticsExt< VALUE, COUNT >::m_statistics.
Referenced by SgUctTreeStatistics::Write(), and SgUctSearchStat::Write().
Member Data Documentation
template<typename VALUE, typename COUNT> VALUE SgStatisticsExt< VALUE, COUNT >::m_max [private]
Definition at line 401 of file SgStatistics.h.
Referenced by SgStatisticsExt< VALUE, COUNT >::Add(), SgStatisticsExt< VALUE, COUNT >::Clear(), SgStatisticsExt< VALUE, COUNT >::Max(), and SgStatisticsExt< VALUE, COUNT >::Write().
template<typename VALUE, typename COUNT> VALUE SgStatisticsExt< VALUE, COUNT >::m_min [private]
Definition at line 403 of file SgStatistics.h.
Referenced by SgStatisticsExt< VALUE, COUNT >::Add(), SgStatisticsExt< VALUE, COUNT >::Clear(), SgStatisticsExt< VALUE, COUNT >::Min(), and SgStatisticsExt< VALUE, COUNT >::Write().
template<typename VALUE, typename COUNT> SgStatistics<VALUE,COUNT> SgStatisticsExt< VALUE, COUNT >::m_statistics [private]
Definition at line 399 of file SgStatistics.h.
Referenced by SgStatisticsExt< VALUE, COUNT >::Add(), SgStatisticsExt< VALUE, COUNT >::Clear(), SgStatisticsExt< VALUE, COUNT >::Count(), SgStatisticsExt< VALUE, COUNT >::Deviation(), SgStatisticsExt< VALUE, COUNT >::IsDefined(), SgStatisticsExt< VALUE, COUNT >::Mean(), SgStatisticsExt< VALUE, COUNT >::Variance(), and SgStatisticsExt< VALUE, COUNT >::Write().
The documentation for this class was generated from the following file:
SgStatistics.h
Sun Mar 13 2011 Doxygen 1.7.1