SmartGame Library: SgSimpleSet Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgSimpleSet Class Reference
Point set efficient for marking and testing.
#include <SgPointSet.h>
Public Member Functions
SgSimpleSet ()
void Include (SgPoint p)
void Exclude (SgPoint p)
bool Contains (SgPoint p) const
void Clear ()
bool IsEmpty () const
bool NonEmpty () const
void GetPoints (SgPointSet *points) const
bool NewMark (SgPoint p)
Private Attributes
bool m_mark [SG_MAXPOINT]
Marked points.
Detailed Description
Point set efficient for marking and testing.
A SgSimpleSet is like a SgPointSet, except that it's more efficient at marking points and testing for marked points, while taking more time to clear, and not providing bit operations on the whole set.
Definition at line 512 of file SgPointSet.h.
Constructor & Destructor Documentation
SgSimpleSet::SgSimpleSet ()
Definition at line 538 of file SgPointSet.h.
References Clear().
Member Function Documentation
void SgSimpleSet::Clear ()
Definition at line 561 of file SgPointSet.h.
References m_mark, and SG_MAXPOINT.
Referenced by SgSimpleSet().
bool SgSimpleSet::Contains (SgPoint p) const
Definition at line 556 of file SgPointSet.h.
References m_mark.
Referenced by GetPoints(), IsEmpty(), and NewMark().
void SgSimpleSet::Exclude (SgPoint p)
Definition at line 550 of file SgPointSet.h.
References m_mark, and SG_ASSERT_BOARDRANGE.
void SgSimpleSet::GetPoints (SgPointSet * points) const
Definition at line 579 of file SgPointSet.h.
References SgPointSet::Clear(), Contains(), SgPointSet::Include(), and SG_MAXPOINT.
void SgSimpleSet::Include (SgPoint p)
Definition at line 544 of file SgPointSet.h.
References m_mark, and SG_ASSERT_BOARDRANGE.
Referenced by NewMark().
bool SgSimpleSet::IsEmpty () const
Definition at line 566 of file SgPointSet.h.
References Contains(), and SG_MAXPOINT.
Referenced by NonEmpty().
bool SgSimpleSet::NewMark (SgPoint p)
Definition at line 587 of file SgPointSet.h.
References Contains(), and Include().
bool SgSimpleSet::NonEmpty () const
Definition at line 574 of file SgPointSet.h.
References IsEmpty().
Member Data Documentation
bool SgSimpleSet::m_mark[SG_MAXPOINT] [private]
Marked points.
Definition at line 535 of file SgPointSet.h.
Referenced by Clear(), Contains(), Exclude(), and Include().
The documentation for this class was generated from the following file:
SgPointSet.h
Sun Mar 13 2011 Doxygen 1.7.1