SmartGame Library: SgUctTreeStatistics Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgUctTreeStatistics Class Reference
[Monte Carlo tree search]
Statistical properties of a SgUctTree.
#include <SgUctTreeUtil.h>
Public Member Functions
SgUctTreeStatistics ()
void Clear ()
void Compute (const SgUctTree &tree)
Clear statistics and traverse tree to compute statistics.
void Write (std::ostream &out) const
Public Attributes
std::size_t m_nuNodes
std::size_t m_moveCounts [MAX_MOVECOUNT]
Number of nodes that have a certain move count.
SgStatisticsExt< SgUctValue,
std::size_t > m_biasRave
Difference between move value and RAVE value.
Static Public Attributes
static const std::size_t MAX_MOVECOUNT = 5
See m_posCounts.
Related Functions
(Note that these are not member functions.)
std::ostream & operator<< (std::ostream &out, const SgUctTreeStatistics &stat)
Write a SgUctTreeStatistics.
Detailed Description
Statistical properties of a SgUctTree.
Definition at line 21 of file SgUctTreeUtil.h.
Constructor & Destructor Documentation
SgUctTreeStatistics::SgUctTreeStatistics ()
Definition at line 16 of file SgUctTreeUtil.cpp.
References Clear().
Member Function Documentation
void SgUctTreeStatistics::Clear ()
Definition at line 21 of file SgUctTreeUtil.cpp.
References SgStatisticsExt< VALUE, COUNT >::Clear(), m_biasRave, m_moveCounts, m_nuNodes, and MAX_MOVECOUNT.
Referenced by Compute(), and SgUctTreeStatistics().
void SgUctTreeStatistics::Compute (const SgUctTree & tree)
Clear statistics and traverse tree to compute statistics.
Definition at line 29 of file SgUctTreeUtil.cpp.
References SgStatisticsExt< VALUE, COUNT >::Add(), Clear(), SgUctNode::HasChildren(), SgUctNode::HasMean(), SgUctNode::HasRaveValue(), SgUctSearch::InverseEstimate(), m_biasRave, m_moveCounts, m_nuNodes, MAX_MOVECOUNT, SgUctNode::Mean(), SgUctNode::MoveCount(), and SgUctNode::RaveValue().
void SgUctTreeStatistics::Write (std::ostream & out) const
Definition at line 55 of file SgUctTreeUtil.cpp.
References m_biasRave, m_moveCounts, m_nuNodes, MAX_MOVECOUNT, and SgStatisticsExt< VALUE, COUNT >::Write().
Referenced by operator<<().
Friends And Related Function Documentation
std::ostream & operator<< (std::ostream & out, const SgUctTreeStatistics & stat) [related]
Write a SgUctTreeStatistics.
Definition at line 71 of file SgUctTreeUtil.cpp.
Member Data Documentation
SgStatisticsExt<SgUctValue,std::size_t> SgUctTreeStatistics::m_biasRave
Difference between move value and RAVE value.
Definition at line 33 of file SgUctTreeUtil.h.
Referenced by Clear(), Compute(), and Write().
std::size_t SgUctTreeStatistics::m_moveCounts[MAX_MOVECOUNT]
Number of nodes that have a certain move count.
Definition at line 30 of file SgUctTreeUtil.h.
Referenced by Clear(), Compute(), and Write().
std::size_t SgUctTreeStatistics::m_nuNodes
Definition at line 27 of file SgUctTreeUtil.h.
Referenced by Clear(), Compute(), and Write().
const std::size_t SgUctTreeStatistics::MAX_MOVECOUNT = 5 [static]
See m_posCounts.
Definition at line 25 of file SgUctTreeUtil.h.
Referenced by Clear(), Compute(), and Write().
The documentation for this class was generated from the following files:
SgUctTreeUtil.h
SgUctTreeUtil.cpp
Sun Mar 13 2011 Doxygen 1.7.1