SmartGame Library: SgSearchHashData Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgSearchHashData Class Reference
Hash data used in class SgSearch.
#include <SgSearch.h>
Public Member Functions
SgSearchHashData ()
SgSearchHashData (int depth, signed value, SgMove bestMove, bool isOnlyUpperBound=false, bool isOnlyLowerBound=false, bool isExactValue=false)
~SgSearchHashData ()
int Depth () const
int Value () const
SgMove BestMove () const
bool IsOnlyUpperBound () const
bool IsOnlyLowerBound () const
void AdjustBounds (int *lower, int *upper)
bool IsBetterThan (const SgSearchHashData &data) const
bool IsValid () const
bool IsExactValue () const
void Invalidate ()
void AgeData ()
Private Attributes
unsigned m_depth: 12
unsigned m_isUpperBound: 1
unsigned m_isLowerBound: 1
unsigned m_isValid: 1
unsigned m_isExactValue: 1
signed m_value: 16
SgMove m_bestMove
Detailed Description
Hash data used in class SgSearch.
Definition at line 75 of file SgSearch.h.
Constructor & Destructor Documentation
SgSearchHashData::SgSearchHashData ()
Definition at line 127 of file SgSearch.h.
SgSearchHashData::SgSearchHashData (int depth, signed value, SgMove bestMove, bool isOnlyUpperBound = false, bool isOnlyLowerBound = false, bool isExactValue = false)
Definition at line 137 of file SgSearch.h.
References m_value, and SG_ASSERT.
SgSearchHashData::~SgSearchHashData ()
Definition at line 156 of file SgSearch.h.
Member Function Documentation
void SgSearchHashData::AdjustBounds (int * lower, int * upper)
Definition at line 185 of file SgSearch.h.
References IsOnlyLowerBound(), IsOnlyUpperBound(), and Value().
Referenced by SgSearch::SearchEngine().
void SgSearchHashData::AgeData ()
Definition at line 213 of file SgSearch.h.
References m_depth.
SgMove SgSearchHashData::BestMove () const
Definition at line 170 of file SgSearch.h.
References m_bestMove.
Referenced by SgSearch::SearchEngine().
int SgSearchHashData::Depth () const
Definition at line 160 of file SgSearch.h.
References m_depth.
Referenced by SgSearch::SearchEngine().
void SgSearchHashData::Invalidate ()
Definition at line 208 of file SgSearch.h.
References m_isValid.
bool SgSearchHashData::IsBetterThan (const SgSearchHashData & data) const
Definition at line 70 of file SgSearch.cpp.
References m_depth, m_isLowerBound, m_isUpperBound, and m_value.
bool SgSearchHashData::IsExactValue () const
Definition at line 203 of file SgSearch.h.
References m_isExactValue.
Referenced by SgSearch::SearchEngine().
bool SgSearchHashData::IsOnlyLowerBound () const
Definition at line 180 of file SgSearch.h.
References m_isLowerBound.
Referenced by AdjustBounds().
bool SgSearchHashData::IsOnlyUpperBound () const
Definition at line 175 of file SgSearch.h.
References m_isUpperBound.
Referenced by AdjustBounds().
bool SgSearchHashData::IsValid () const
Definition at line 198 of file SgSearch.h.
References m_isValid.
Referenced by SgSearch::LookupHash(), and SgSearch::SearchEngine().
int SgSearchHashData::Value () const
Definition at line 165 of file SgSearch.h.
References m_value.
Referenced by AdjustBounds(), and SgSearch::SearchEngine().
Member Data Documentation
SgMove SgSearchHashData::m_bestMove [private]
Definition at line 122 of file SgSearch.h.
Referenced by BestMove().
unsigned SgSearchHashData::m_depth [private]
Definition at line 110 of file SgSearch.h.
Referenced by AgeData(), Depth(), and IsBetterThan().
unsigned SgSearchHashData::m_isExactValue [private]
Definition at line 118 of file SgSearch.h.
Referenced by IsExactValue().
unsigned SgSearchHashData::m_isLowerBound [private]
Definition at line 114 of file SgSearch.h.
Referenced by IsBetterThan(), and IsOnlyLowerBound().
unsigned SgSearchHashData::m_isUpperBound [private]
Definition at line 112 of file SgSearch.h.
Referenced by IsBetterThan(), and IsOnlyUpperBound().
unsigned SgSearchHashData::m_isValid [private]
Definition at line 116 of file SgSearch.h.
Referenced by Invalidate(), and IsValid().
signed SgSearchHashData::m_value [private]
Definition at line 120 of file SgSearch.h.
Referenced by IsBetterThan(), SgSearchHashData(), and Value().
The documentation for this class was generated from the following files:
SgSearch.h
SgSearch.cpp
Sun Mar 13 2011 Doxygen 1.7.1