SmartGame Library: SgVectorIteratorOf< T > Class Template Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgVectorIteratorOf< T > Class Template Reference
Iterator for VectorOf<T> typed vector of pointers to T.
#include <SgVector.h>
Public Member Functions
SgVectorIteratorOf (const SgVectorOf< T > &vector)
Create a vector iterator to iterate through vector.
void operator++ ()
Advance the state of the iteration to the next element.
T * operator* () const
Return the value of the current element.
operator bool () const
Return true if iteration is valid, otherwise false.
Detailed Description
template<class T>
class SgVectorIteratorOf< T >
Iterator for VectorOf<T> typed vector of pointers to T.
Definition at line 439 of file SgVector.h.
Constructor & Destructor Documentation
template<class T> SgVectorIteratorOf< T >::SgVectorIteratorOf (const SgVectorOf< T > & vector)
Create a vector iterator to iterate through vector.
Definition at line 444 of file SgVector.h.
Member Function Documentation
template<class T> SgVectorIteratorOf< T >::operator bool () const
Return true if iteration is valid, otherwise false.
Reimplemented from SgVectorIterator< void * >.
Definition at line 458 of file SgVector.h.
Referenced by SgVectorIteratorOf< SgProp >::operator bool().
template<class T> T* SgVectorIteratorOf< T >::operator* () const
Return the value of the current element.
Reimplemented from SgVectorIterator< void * >.
Definition at line 453 of file SgVector.h.
Referenced by SgVectorIteratorOf< SgProp >::operator*().
template<class T> void SgVectorIteratorOf< T >::operator++ ()
Advance the state of the iteration to the next element.
Reimplemented from SgVectorIterator< void * >.
Definition at line 448 of file SgVector.h.
Referenced by SgVectorIteratorOf< SgProp >::operator++().
The documentation for this class was generated from the following file:
SgVector.h
Sun Mar 13 2011 Doxygen 1.7.1