SmartGame Library: SgSetIterator Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgSetIterator Class Reference
Iterator to iterate through 'set'.
#include <SgPointSet.h>
Public Member Functions
SgSetIterator (const SgPointSet &set)
Set may contain only board points, no 'Border' points.
void operator++ ()
Advance the state of the iteration to the next element.
SgPoint operator* () const
Return the value of the current element.
operator bool () const
Return true if iteration is valid, otherwise false.
Private Member Functions
void FindNext ()
int Size () const
Private Attributes
const SgPointSet & m_set
int m_index
Detailed Description
Iterator to iterate through 'set'.
Set may contain only board points, no 'Border' points.
Definition at line 440 of file SgPointSet.h.
Constructor & Destructor Documentation
SgSetIterator::SgSetIterator (const SgPointSet & set)
Set may contain only board points, no 'Border' points.
Definition at line 465 of file SgPointSet.h.
References FindNext().
Member Function Documentation
void SgSetIterator::FindNext () [private]
Definition at line 491 of file SgPointSet.h.
References SgPointSet::m_a, m_index, m_set, and Size().
Referenced by operator++(), and SgSetIterator().
SgSetIterator::operator bool () const
Return true if iteration is valid, otherwise false.
Definition at line 486 of file SgPointSet.h.
References m_index, and Size().
SgPoint SgSetIterator::operator* () const
Return the value of the current element.
Definition at line 478 of file SgPointSet.h.
References SgPointSet::m_a, m_index, m_set, SG_ASSERT, SG_ASSERT_BOARDRANGE, and Size().
void SgSetIterator::operator++ ()
Advance the state of the iteration to the next element.
Definition at line 472 of file SgPointSet.h.
References FindNext(), m_index, SG_ASSERT, and Size().
int SgSetIterator::Size () const [private]
Definition at line 501 of file SgPointSet.h.
References SgPointSet::m_a, and m_set.
Referenced by FindNext(), operator bool(), operator*(), and operator++().
Member Data Documentation
int SgSetIterator::m_index [private]
Definition at line 458 of file SgPointSet.h.
Referenced by FindNext(), operator bool(), operator*(), and operator++().
const SgPointSet& SgSetIterator::m_set [private]
Definition at line 456 of file SgPointSet.h.
Referenced by FindNext(), operator*(), and Size().
The documentation for this class was generated from the following file:
SgPointSet.h
Sun Mar 13 2011 Doxygen 1.7.1