SmartGame Library: SgPointUtil::PointToCol Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgPointUtil::PointToCol Class Reference
Lookup table internally used by SgPointUtil::Col().
#include <SgPoint.h>
Public Member Functions
PointToCol ()
SgGrid Col (SgPoint p) const
Private Attributes
SgArray< SgGrid, SG_MAXPOINT > m_col
Detailed Description
Lookup table internally used by SgPointUtil::Col().
Definition at line 248 of file SgPoint.h.
Constructor & Destructor Documentation
SgPointUtil::PointToCol::PointToCol ()
Definition at line 251 of file SgPoint.h.
References SgArray< T, SIZE >::Fill(), m_col, SgPointUtil::Pt(), and SG_MAX_SIZE.
Member Function Documentation
SgGrid SgPointUtil::PointToCol::Col (SgPoint p) const
Definition at line 259 of file SgPoint.h.
References m_col, SG_ASSERT, and SG_ASSERT_BOARDRANGE.
Referenced by SgPointUtil::Col().
Member Data Documentation
SgArray<SgGrid,SG_MAXPOINT> SgPointUtil::PointToCol::m_col [private]
Definition at line 267 of file SgPoint.h.
Referenced by Col(), and PointToCol().
The documentation for this class was generated from the following file:
SgPoint.h
Sun Mar 13 2011 Doxygen 1.7.1