SmartGame Library: SgBWSet Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgBWSet Class Reference
Pair of SgPointSet's indexed by color SG_BLACK, SG_WHITE.
#include <SgBWSet.h>
Public Member Functions
SgBWSet ()
SgBWSet (const SgPointSet &black, const SgPointSet &white)
const SgPointSet & operator[] (SgBlackWhite c) const
SgPointSet & operator[] (SgBlackWhite c)
bool operator== (const SgBWSet &other) const
bool operator!= (const SgBWSet &other) const
SgBWSet & operator|= (const SgBWSet &other)
void Clear ()
bool BothEmpty () const
bool Disjoint () const
void AssertDisjoint () const
SgPointSet Both () const
bool OneContains (SgPoint p) const
bool BothContain (SgPoint p) const
Private Attributes
SgBWArray< SgPointSet > m_set
Detailed Description
Pair of SgPointSet's indexed by color SG_BLACK, SG_WHITE.
Definition at line 16 of file SgBWSet.h.
Constructor & Destructor Documentation
SgBWSet::SgBWSet ()
Definition at line 14 of file SgBWSet.h.
SgBWSet::SgBWSet (const SgPointSet & black, const SgPointSet & white)
Definition at line 18 of file SgBWSet.h.
Member Function Documentation
void SgBWSet::AssertDisjoint () const
Definition at line 57 of file SgBWSet.h.
References m_set, SG_BLACK, and SG_WHITE.
SgPointSet SgBWSet::Both () const
Definition at line 62 of file SgBWSet.h.
References Disjoint(), and SG_ASSERT.
bool SgBWSet::BothContain (SgPoint p) const
Definition at line 73 of file SgBWSet.h.
References m_set, SG_BLACK, and SG_WHITE.
bool SgBWSet::BothEmpty () const
Definition at line 45 of file SgBWSet.h.
References m_set, SG_BLACK, and SG_WHITE.
void SgBWSet::Clear ()
Definition at line 39 of file SgBWSet.h.
bool SgBWSet::Disjoint () const
Definition at line 52 of file SgBWSet.h.
Referenced by Both().
bool SgBWSet::OneContains (SgPoint p) const
Definition at line 67 of file SgBWSet.h.
References m_set, SG_BLACK, and SG_WHITE.
bool SgBWSet::operator!= (const SgBWSet & other) const
Definition at line 94 of file SgBWSet.h.
References operator==().
bool SgBWSet::operator== (const SgBWSet & other) const
Definition at line 88 of file SgBWSet.h.
References m_set, SG_BLACK, and SG_WHITE.
Referenced by operator!=().
SgPointSet& SgBWSet::operator[] (SgBlackWhite c)
Definition at line 28 of file SgBWSet.h.
References m_set.
const SgPointSet& SgBWSet::operator[] (SgBlackWhite c) const
Definition at line 23 of file SgBWSet.h.
SgBWSet & SgBWSet::operator|= (const SgBWSet & other)
Definition at line 99 of file SgBWSet.h.
References m_set, SG_BLACK, and SG_WHITE.
Member Data Documentation
SgBWArray<SgPointSet> SgBWSet::m_set [private]
Definition at line 80 of file SgBWSet.h.
Referenced by AssertDisjoint(), BothContain(), BothEmpty(), OneContains(), operator==(), operator[](), and operator|=().
The documentation for this class was generated from the following file:
SgBWSet.h
Sun Mar 13 2011 Doxygen 1.7.1