SmartGame Library: SgPointSet::PrecompAllPoints Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgPointSet::PrecompAllPoints Class Reference
Precomputed point sets with all points depending on board size.
Public Member Functions
PrecompAllPoints ()
const SgPointSet & Get (int boardSize)
Private Attributes
SgArray< std::auto_ptr
< SgPointSet >, SG_MAX_SIZE+1 > m_allPoints
Detailed Description
Precomputed point sets with all points depending on board size.
Definition at line 179 of file SgPointSet.h.
Constructor & Destructor Documentation
SgPointSet::PrecompAllPoints::PrecompAllPoints ()
Definition at line 28 of file SgPointSet.cpp.
References SgPointSet::Include(), m_allPoints, SgPointUtil::Pt(), SG_MAX_SIZE, SG_MIN_SIZE, and SgPointSet::SgPointSet().
Member Function Documentation
const SgPointSet& SgPointSet::PrecompAllPoints::Get (int boardSize)
Definition at line 184 of file SgPointSet.h.
References m_allPoints, SG_ASSERT, SG_MAX_SIZE, and SG_MIN_SIZE.
Referenced by SgPointSet::AllPoints().
Member Data Documentation
SgArray<std::auto_ptr<SgPointSet>,SG_MAX_SIZE + 1> SgPointSet::PrecompAllPoints::m_allPoints [private]
Definition at line 192 of file SgPointSet.h.
Referenced by Get(), and PrecompAllPoints().
The documentation for this class was generated from the following files:
SgPointSet.h
SgPointSet.cpp
Sun Mar 13 2011 Doxygen 1.7.1