SmartGame Library: SgReadPointSet Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgReadPointSet Class Reference
Read all points in set.
#include <SgPointSetUtil.h>
Public Member Functions
SgReadPointSet (SgPointSet &pointSet)
std::istream & Read (std::istream &in) const
Private Attributes
SgPointSet & m_pointSet
Related Functions
(Note that these are not member functions.)
std::istream & operator>> (std::istream &in, const SgReadPointSet &Read)
Detailed Description
Read all points in set.
Definition at line 59 of file SgPointSetUtil.h.
Constructor & Destructor Documentation
SgReadPointSet::SgReadPointSet (SgPointSet & pointSet)
Definition at line 81 of file SgPointSetUtil.cpp.
Member Function Documentation
istream & SgReadPointSet::Read (std::istream & in) const
Definition at line 86 of file SgPointSetUtil.cpp.
References SgPointSet::Include(), m_pointSet, and SgPointUtil::Pt().
Referenced by operator>>().
Friends And Related Function Documentation
std::istream & operator>> (std::istream & in, const SgReadPointSet & Read) [related]
Definition at line 108 of file SgPointSetUtil.cpp.
Member Data Documentation
SgPointSet& SgReadPointSet::m_pointSet [mutable, private]
Definition at line 67 of file SgPointSetUtil.h.
Referenced by Read().
The documentation for this class was generated from the following files:
SgPointSetUtil.h
SgPointSetUtil.cpp
Sun Mar 13 2011 Doxygen 1.7.1