SmartGame Library: SgArray< T, SIZE > Class Template Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgArray< T, SIZE > Class Template Reference
Static array.
#include <SgArray.h>
Classes
class Iterator
Local const iterator.
class NonConstIterator
Local non-const iterator.
Public Member Functions
SgArray ()
SgArray (const SgArray &array)
SgArray (const T &val)
SgArray & operator= (const SgArray &array)
T & operator[] (int index)
const T & operator[] (int index) const
SgArray & operator*= (T val)
void Fill (const T &val)
Private Attributes
T m_array [SIZE]
Friends
class Iterator
class NonConstIterator
Detailed Description
template<typename T, int SIZE>
class SgArray< T, SIZE >
Static array.
Wrapper class around a C style array. Uses assertions for indices in range in debug mode.
Deprecated:
Use boost::array instead
Definition at line 84 of file SgArray.h.
Constructor & Destructor Documentation
template<typename T , int SIZE> SgArray< T, SIZE >::SgArray ()
Definition at line 198 of file SgArray.h.
template<typename T , int SIZE> SgArray< T, SIZE >::SgArray (const SgArray< T, SIZE > & array)
Definition at line 203 of file SgArray.h.
References SG_ASSERT.
template<typename T, int SIZE> SgArray< T, SIZE >::SgArray (const T & val) [explicit]
Definition at line 210 of file SgArray.h.
References SgArray< T, SIZE >::Fill().
Member Function Documentation
template<typename T, int SIZE> void SgArray< T, SIZE >::Fill (const T & val)
Definition at line 249 of file SgArray.h.
References SgArray< T, SIZE >::m_array.
Referenced by SgBoardConst::BoardConstImpl::BoardConstImpl(), SgMarker::Init(), SgPointUtil::PointToCol::PointToCol(), SgPointUtil::PointToRow::PointToRow(), and SgArray< T, SIZE >::SgArray().
template<typename T, int SIZE> SgArray< T, SIZE > & SgArray< T, SIZE >::operator*= (T val)
Definition at line 240 of file SgArray.h.
References SgArray< T, SIZE >::m_array.
template<typename T , int SIZE> SgArray< T, SIZE > & SgArray< T, SIZE >::operator= (const SgArray< T, SIZE > & array)
Definition at line 216 of file SgArray.h.
References SgArray< T, SIZE >::m_array, and SG_ASSERT.
template<typename T , int SIZE> const T & SgArray< T, SIZE >::operator[] (int index) const
Definition at line 232 of file SgArray.h.
References SgArray< T, SIZE >::m_array, and SG_ASSERT.
template<typename T , int SIZE> T & SgArray< T, SIZE >::operator[] (int index)
Definition at line 224 of file SgArray.h.
References SgArray< T, SIZE >::m_array, and SG_ASSERT.
Friends And Related Function Documentation
template<typename T, int SIZE> friend class Iterator [friend]
Definition at line 140 of file SgArray.h.
template<typename T, int SIZE> friend class NonConstIterator [friend]
Definition at line 141 of file SgArray.h.
Member Data Documentation
template<typename T, int SIZE> T SgArray< T, SIZE >::m_array[SIZE] [private]
Definition at line 143 of file SgArray.h.
Referenced by SgArray< T, SIZE >::Fill(), SgArray< T, SIZE >::operator*=(), SgArray< T, SIZE >::operator=(), and SgArray< T, SIZE >::operator[]().
The documentation for this class was generated from the following file:
SgArray.h
Sun Mar 13 2011 Doxygen 1.7.1