SmartGame Library: SgSearchControl Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgSearchControl Class Reference
Resource control used in class SgSearch.
#include <SgSearchControl.h>
Public Member Functions
SgSearchControl ()
virtual ~SgSearchControl ()
virtual bool Abort (double elapsedTime, int numNodes)=0
Check if search should be aborted.
virtual bool StartNextIteration (int depth, double elapsedTime, int numNodes)
Check if next iteration should be started.
Private Member Functions
SgSearchControl (const SgSearchControl &)
Not implemented.
SgSearchControl & operator= (const SgSearchControl &)
Not implemented.
Detailed Description
Resource control used in class SgSearch.
Definition at line 16 of file SgSearchControl.h.
Constructor & Destructor Documentation
SgSearchControl::SgSearchControl ()
Definition at line 44 of file SgSearchControl.h.
SgSearchControl::~SgSearchControl () [virtual]
Definition at line 11 of file SgSearchControl.cpp.
SgSearchControl::SgSearchControl (const SgSearchControl &) [private]
Not implemented.
Member Function Documentation
virtual bool SgSearchControl::Abort (double elapsedTime, int numNodes) [pure virtual]
Check if search should be aborted.
Called at each node.
Implemented in SgTimeSearchControl, SgNodeSearchControl, SgCombinedSearchControl, and SgRelaxedSearchControl.
Referenced by SgSearch::AbortSearch().
SgSearchControl& SgSearchControl::operator= (const SgSearchControl &) [private]
Not implemented.
bool SgSearchControl::StartNextIteration (int depth, double elapsedTime, int numNodes) [virtual]
Check if next iteration should be started.
Called before each iteration. The default implementation always returns true.
Parameters:
depth The depth of the next iteration.
elapsedTime The elapsed time in seconds.
numNodes The number of nodes visited.
Definition at line 15 of file SgSearchControl.cpp.
References SG_UNUSED().
Referenced by SgSearch::IteratedSearch().
The documentation for this class was generated from the following files:
SgSearchControl.h
SgSearchControl.cpp
Sun Mar 13 2011 Doxygen 1.7.1