SmartGame Library: SgMpiNullSynchronizer Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgMpiNullSynchronizer Class Reference
Synchronizer with empty implementation.
#include <SgMpiSynchronizer.h>
Public Member Functions
SgMpiNullSynchronizer ()
virtual ~SgMpiNullSynchronizer ()
virtual std::string ToNodeFilename (const std::string &filename) const
virtual bool IsRootProcess () const
virtual void OnStartSearch (SgUctSearch &search)
virtual void OnEndSearch (SgUctSearch &search)
virtual void OnThreadStartSearch (SgUctSearch &search, SgUctThreadState &state)
virtual void OnThreadEndSearch (SgUctSearch &search, SgUctThreadState &state)
virtual void OnSearchIteration (SgUctSearch &search, SgUctValue gameNumber, int threadId, const SgUctGameInfo &info)
virtual void OnStartPonder ()
virtual void OnEndPonder ()
virtual void WriteStatistics (std::ostream &out) const
virtual void SynchronizeUserAbort (bool &flag)
virtual void SynchronizePassWins (bool &flag)
virtual void SynchronizeEarlyPassPossible (bool &flag)
virtual void SynchronizeMove (SgMove &move)
virtual void SynchronizeValue (SgUctValue &value)
virtual void SynchronizeSearchStatus (SgUctValue &value, bool &earlyAbort, SgUctValue &rootMoveCount)
Static Public Member Functions
static SgMpiSynchronizerHandle Create ()
Detailed Description
Synchronizer with empty implementation.
Definition at line 77 of file SgMpiSynchronizer.h.
Constructor & Destructor Documentation
SgMpiNullSynchronizer::SgMpiNullSynchronizer ()
Definition at line 18 of file SgMpiSynchronizer.cpp.
Referenced by Create().
SgMpiNullSynchronizer::~SgMpiNullSynchronizer () [virtual]
Definition at line 22 of file SgMpiSynchronizer.cpp.
Member Function Documentation
SgMpiSynchronizerHandle SgMpiNullSynchronizer::Create () [static]
Definition at line 26 of file SgMpiSynchronizer.cpp.
References SgMpiNullSynchronizer().
bool SgMpiNullSynchronizer::IsRootProcess () const [virtual]
Implements SgMpiSynchronizer.
Definition at line 37 of file SgMpiSynchronizer.cpp.
void SgMpiNullSynchronizer::OnEndPonder () [virtual]
Implements SgMpiSynchronizer.
Definition at line 81 of file SgMpiSynchronizer.cpp.
void SgMpiNullSynchronizer::OnEndSearch (SgUctSearch & search) [virtual]
Implements SgMpiSynchronizer.
Definition at line 47 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::OnSearchIteration (SgUctSearch & search, SgUctValue gameNumber, int threadId, const SgUctGameInfo & info) [virtual]
Implements SgMpiSynchronizer.
Definition at line 66 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::OnStartPonder () [virtual]
Implements SgMpiSynchronizer.
Definition at line 77 of file SgMpiSynchronizer.cpp.
void SgMpiNullSynchronizer::OnStartSearch (SgUctSearch & search) [virtual]
Implements SgMpiSynchronizer.
Definition at line 42 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::OnThreadEndSearch (SgUctSearch & search, SgUctThreadState & state) [virtual]
Implements SgMpiSynchronizer.
Definition at line 59 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::OnThreadStartSearch (SgUctSearch & search, SgUctThreadState & state) [virtual]
Implements SgMpiSynchronizer.
Definition at line 52 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::SynchronizeEarlyPassPossible (bool & flag) [virtual]
Implements SgMpiSynchronizer.
Definition at line 101 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::SynchronizeMove (SgMove & move) [virtual]
Implements SgMpiSynchronizer.
Definition at line 107 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::SynchronizePassWins (bool & flag) [virtual]
Implements SgMpiSynchronizer.
Definition at line 95 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::SynchronizeSearchStatus (SgUctValue & value, bool & earlyAbort, SgUctValue & rootMoveCount) [virtual]
Implements SgMpiSynchronizer.
Definition at line 117 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::SynchronizeUserAbort (bool & flag) [virtual]
Implements SgMpiSynchronizer.
Definition at line 90 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
void SgMpiNullSynchronizer::SynchronizeValue (SgUctValue & value) [virtual]
Implements SgMpiSynchronizer.
Definition at line 112 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
string SgMpiNullSynchronizer::ToNodeFilename (const std::string & filename) const [virtual]
Implements SgMpiSynchronizer.
Definition at line 32 of file SgMpiSynchronizer.cpp.
void SgMpiNullSynchronizer::WriteStatistics (std::ostream & out) const [virtual]
Implements SgMpiSynchronizer.
Definition at line 85 of file SgMpiSynchronizer.cpp.
References SG_UNUSED().
The documentation for this class was generated from the following files:
SgMpiSynchronizer.h
SgMpiSynchronizer.cpp
Sun Mar 13 2011 Doxygen 1.7.1