SmartGame Library: SgUtil Namespace Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgUtil Namespace Reference
Functions
template<class T >
void ForceInRange (const T &min, T *p, const T &max)
template<class T >
bool InRange (const T &i, const T &from, const T &to)
template<class T >
void LowerLimit (T &x, const T &limit)
template<class T >
void UpperLimit (T &x, const T &limit)
Function Documentation
template<class T > void SgUtil::ForceInRange (const T & min, T * p, const T & max)
Definition at line 17 of file SgUtil.h.
template<class T > bool SgUtil::InRange (const T & i, const T & from, const T & to)
Definition at line 26 of file SgUtil.h.
Referenced by SgPointUtil::InBoardRange(), SgReadPoint::Read(), SgPropUtil::SgfStringToPoint(), and SgUctSearch::UpdateRaveValues().
template<class T > void SgUtil::LowerLimit (T & x, const T & limit)
Definition at line 32 of file SgUtil.h.
template<class T > void SgUtil::UpperLimit (T & x, const T & limit)
Definition at line 39 of file SgUtil.h.
Sun Mar 13 2011 Doxygen 1.7.1