SmartGame Library: SgVectorUtil Namespace Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgVectorUtil Namespace Reference
Functions
void Difference (SgVector< int > *vector, const SgVector< int > &vector2)
Exclude all elements of vector2 from vector.
void Intersection (SgVector< int > *vector, const SgVector< int > &vector2)
Keep only elements in vector that also occur in vector2.
Function Documentation
void SgVectorUtil::Difference (SgVector< int > * vector, const SgVector< int > & vector2)
Exclude all elements of vector2 from vector.
Definition at line 13 of file SgVectorUtil.cpp.
References SgVector< T >::Exclude().
void SgVectorUtil::Intersection (SgVector< int > * vector, const SgVector< int > & vector2)
Keep only elements in vector that also occur in vector2.
Definition at line 21 of file SgVectorUtil.cpp.
References SgVector< T >::Contains(), SgVector< T >::PushBack(), and SgVector< T >::SwapWith().
Sun Mar 13 2011 Doxygen 1.7.1