SmartGame Library: SgDebug.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgDebug.cpp File Reference
See SgDebug.h.
#include "SgSystem.h"
#include "SgDebug.h"
#include <fstream>
#include <iostream>
#include <memory>
Functions
std::ostream & SgDebug ()
Current logging stream.
std::ostream & SgWarning ()
Write warning prefix to logging stream and return it.
void SgDebugToWindow ()
Set logging stream to console window.
void SgDebugToFile (const char *filename)
Set logging stream to file.
void SgDebugToNull ()
Set logging stream to null stream.
ostream * SgSwapDebugStr (ostream *newStr)
Variables
static ofstream s_nullStream
Null stream.
static auto_ptr< ofstream > s_fileStream
ostream *g_debugStrPtr & cerr
Detailed Description
See SgDebug.h.
Definition in file SgDebug.cpp.
Function Documentation
std::ostream& SgDebug ()
Current logging stream.
Definition at line 27 of file SgDebug.cpp.
References SG_ASSERT.
Referenced by SgSearch::AddSequenceToHash(), SgSearch::CallEvaluate(), SgSearch::CallExecute(), SgSearch::CallGenerate(), SgSearch::CallTakeBack(), SgGtpCommands::CmdDebugger(), SgGtpCommands::CmdExec(), SgUctTree::CopySubtree(), SgUctSearch::Debug(), SgThreadedWorker< I, O, W >::DoWork(), SgSearch::LookupHash(), SgUctSearch::Thread::operator()(), SgTimeRecord::PlayedMove(), SgUctSearch::PrintSearchProgress(), SgUctSearch::Search(), SgUctSearch::SearchOnePly(), SgGtpClient::Send(), SgUctTree::SetMaxNodes(), SgRandom::SetSeed(), SgWarning(), SgSearch::StartOfDepth(), SgSearch::StoreHash(), SgUctTree::ThrowConsistencyError(), SgDefaultTimeControl::TimeForCurrentMove(), SgTimeRecord::UpdateTimeLeft(), SgEvaluatedMovesArray::Write(), and SgThreadedWorker< I, O, W >::~SgThreadedWorker().
void SgDebugToFile (const char * filename)
Set logging stream to file.
Definition at line 51 of file SgDebug.cpp.
References s_fileStream.
void SgDebugToNull ()
Set logging stream to null stream.
Discards everything written to SgDebug().
Definition at line 58 of file SgDebug.cpp.
References s_nullStream.
Referenced by SgGtpCommands::CmdQuiet().
void SgDebugToWindow ()
Set logging stream to console window.
Todo:
: Bad function name, uses std::cerr on Unix and std::cout on MAC
Definition at line 46 of file SgDebug.cpp.
References cerr.
ostream* SgSwapDebugStr (ostream * newStr)
Definition at line 63 of file SgDebug.cpp.
Referenced by SgGtpCommands::CmdQuiet(), SgDebugToNewFile::SetFile(), SgDebugToString::SgDebugToString(), SgDebugToNewFile::~SgDebugToNewFile(), and SgDebugToString::~SgDebugToString().
std::ostream& SgWarning ()
Write warning prefix to logging stream and return it.
Writes "WARNING: " to the logging stream and returns it for outputting the rest of the warning line. Lines beginning with this prefix are displayed in a different color than regular stderr output in GoGui.
Definition at line 38 of file SgDebug.cpp.
References SgDebug().
Referenced by SgGameWriter::HandleProps(), and SgUctSearch::StartSearch().
Variable Documentation
ostream* g_debugStrPtr& cerr
Definition at line 25 of file SgDebug.cpp.
Referenced by SgGtpCommands::CmdEchoErr(), SgGtpCommands::CmdQuiet(), SgTime::Get(), SgDebugToWindow(), SgHandleAssertion(), and SgInitImpl().
auto_ptr<ofstream> s_fileStream [static]
Definition at line 22 of file SgDebug.cpp.
Referenced by SgDebugToFile().
ofstream s_nullStream [static]
Null stream.
This file stream will never be opened and acts as a null stream for SgDebug().
Definition at line 20 of file SgDebug.cpp.
Referenced by SgDebugToNull().
Sun Mar 13 2011 Doxygen 1.7.1