SmartGame Library: SgInit.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgInit.cpp File Reference
See SgInit.h.
#include "SgSystem.h"
#include "SgInit.h"
#include <iostream>
#include "SgException.h"
#include "SgMemCheck.h"
#include "SgProp.h"
Functions
void SgFini ()
Call all lower-level Fini functions.
void SgInitImpl (bool compiledInDebugMode)
Used in SgInit(); public only as a side effect of the implementation.
void SgInitCheck ()
Check that SgInit was called.
Detailed Description
See SgInit.h.
Definition in file SgInit.cpp.
Function Documentation
void SgFini ()
Call all lower-level Fini functions.
This function must be called after using the SmartGo module. Also calls SgMemCheck.
Note:
Will become obsolete in the future
See also:
SgInit
Definition at line 26 of file SgInit.cpp.
References SgProp::Fini(), and SgMemCheck().
void SgInitCheck ()
Check that SgInit was called.
Exceptions:
SgException if not
Definition at line 63 of file SgInit.cpp.
Referenced by SgBoardConst::SgBoardConst().
void SgInitImpl (bool compiledInDebugMode)
Used in SgInit(); public only as a side effect of the implementation.
Definition at line 33 of file SgInit.cpp.
References cerr, and SgProp::Init().
Referenced by SgInit().
Sun Mar 13 2011 Doxygen 1.7.1