SmartGame Library: SgPointSetUtil.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgPointSetUtil.h File Reference
Utility functions for SgPointSet.
#include <iosfwd>
#include <string>
#include "SgPointSet.h"
Classes
class SgWritePointSet
Write all points in set.
class SgWritePointSetID
Write center point and size of set.
class SgReadPointSet
Read all points in set.
Namespaces
namespace SgPointSetUtil
Functions
std::ostream & operator<< (std::ostream &out, const SgWritePointSet &write)
std::ostream & operator<< (std::ostream &out, const SgPointSet &set)
std::ostream & operator<< (std::ostream &stream, const SgWritePointSetID &w)
std::istream & operator>> (std::istream &in, const SgReadPointSet &Read)
std::istream & operator>> (std::istream &in, SgPointSet &pointSet)
void SgPointSetUtil::Rotate (int rotation, SgPointSet &pointSet, int boardSize)
Rotate coordinates - see SgPointUtil::Rotate.
Detailed Description
Utility functions for SgPointSet.
Definition in file SgPointSetUtil.h.
Function Documentation
std::ostream& operator<< (std::ostream & out, const SgWritePointSet & write)
Definition at line 54 of file SgPointSetUtil.cpp.
References SgWritePointSet::Write().
std::ostream& operator<< (std::ostream & out, const SgPointSet & set)
Definition at line 59 of file SgPointSetUtil.cpp.
std::ostream& operator<< (std::ostream & stream, const SgWritePointSetID & w)
Definition at line 66 of file SgPointSetUtil.cpp.
References SgPointSet::Center(), SgPointSet::IsEmpty(), SgWritePointSetID::Points(), and SgPointSet::Size().
std::istream& operator>> (std::istream & in, const SgReadPointSet & Read)
Definition at line 108 of file SgPointSetUtil.cpp.
References SgReadPointSet::Read().
std::istream& operator>> (std::istream & in, SgPointSet & pointSet)
Definition at line 113 of file SgPointSetUtil.cpp.
Sun Mar 13 2011 Doxygen 1.7.1