SmartGame Library: SgPointSetUtil.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgPointSetUtil.cpp File Reference
See SgPointSetUtil.h.
#include "SgSystem.h"
#include "SgPointSetUtil.h"
#include <iostream>
#include "SgPointSet.h"
#include "SgWrite.h"
Functions
ostream & operator<< (ostream &out, const SgWritePointSet &write)
ostream & operator<< (ostream &out, const SgPointSet &pointSet)
ostream & operator<< (ostream &stream, const SgWritePointSetID &w)
istream & operator>> (istream &in, const SgReadPointSet &read)
istream & operator>> (istream &in, SgPointSet &pointSet)
Detailed Description
See SgPointSetUtil.h.
Definition in file SgPointSetUtil.cpp.
Function Documentation
std::ostream & operator<< (ostream & out, const SgWritePointSet & write)
Definition at line 54 of file SgPointSetUtil.cpp.
References SgWritePointSet::Write().
std::ostream & operator<< (ostream & out, const SgPointSet & pointSet)
Definition at line 59 of file SgPointSetUtil.cpp.
ostream& operator<< (ostream & stream, const SgWritePointSetID & w)
Definition at line 66 of file SgPointSetUtil.cpp.
References SgPointSet::Center(), SgPointSet::IsEmpty(), SgWritePointSetID::Points(), and SgPointSet::Size().
std::istream & operator>> (istream & in, const SgReadPointSet & read)
Definition at line 108 of file SgPointSetUtil.cpp.
References SgReadPointSet::Read().
istream& operator>> (istream & in, SgPointSet & pointSet)
Definition at line 113 of file SgPointSetUtil.cpp.
Sun Mar 13 2011 Doxygen 1.7.1