SmartGame Library: SgRect.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgRect.h File Reference
Rectangle on the Go board.
#include "SgPoint.h"
Classes
class SgRect
Rectangle on the Go board.
class SgRectIterator
Iterator for rectangle on the Go board, based on SgRect object.
Functions
std::ostream & operator<< (std::ostream &stream, const SgRect &rect)
Detailed Description
Rectangle on the Go board.
Definition in file SgRect.h.
Function Documentation
std::ostream& operator<< (std::ostream & stream, const SgRect & rect)
Definition at line 23 of file SgRect.cpp.
References SgRect::Bottom(), SgRect::Left(), SgRect::Right(), and SgRect::Top().
Sun Mar 13 2011 Doxygen 1.7.1