SmartGame Library: SgSearchStatistics.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgSearchStatistics.h File Reference
Search statistics.
#include <iosfwd>
Classes
class SgSearchStatistics
Statistics used in class SgSearch.
Functions
std::ostream & operator<< (std::ostream &stream, const SgSearchStatistics &w)
Detailed Description
Search statistics.
Definition in file SgSearchStatistics.h.
Function Documentation
std::ostream& operator<< (std::ostream & stream, const SgSearchStatistics & w)
Definition at line 95 of file SgSearchStatistics.cpp.
References SgSearchStatistics::DepthReached(), SgTime::Format(), SgSearchStatistics::NumEvals(), SgSearchStatistics::NumEvalsPerSecond(), SgSearchStatistics::NumNodes(), SgSearchStatistics::NumNodesPerSecond(), and SgSearchStatistics::TimeUsed().
Sun Mar 13 2011 Doxygen 1.7.1