SmartGame Library: SgSortedMoves.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgSortedMoves.h File Reference
Sorted table of moves.
#include <iostream>
#include "SgRandom.h"
#include "SgVector.h"
Classes
class SgSortedMoves< MOVE, VALUE, SIZE >
Small array with moves sorted by their value.
Functions
template<typename MOVE , typename VALUE , int SIZE>
std::ostream & operator<< (std::ostream &str, const SgSortedMoves< MOVE, VALUE, SIZE > &m)
write all moves in the table and their values
Detailed Description
Sorted table of moves.
Move tables are used to store a small number of best moves. They have the usual operations Insert, Delete, etc.
Definition in file SgSortedMoves.h.
Function Documentation
template<typename MOVE , typename VALUE , int SIZE> std::ostream& operator<< (std::ostream & str, const SgSortedMoves< MOVE, VALUE, SIZE > & m)
write all moves in the table and their values
Definition at line 386 of file SgSortedMoves.h.
References SgSortedMoves< MOVE, VALUE, SIZE >::Move(), SgSortedMoves< MOVE, VALUE, SIZE >::NuMoves(), and SgSortedMoves< MOVE, VALUE, SIZE >::Value().
Sun Mar 13 2011 Doxygen 1.7.1