SmartGame Library: SgTimeRecord.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgTimeRecord.h File Reference
Time management.
#include <iosfwd>
#include "SgBWArray.h"
Classes
class SgTimeRecord
A time record contains time-related information.
Enumerations
enum SgClockState { SG_CLOCK_OFF, SG_CLOCK_RUNNING, SG_CLOCK_SUSPENDED }
Clock states.
Functions
std::ostream & operator<< (std::ostream &out, const SgTimeRecord &time)
Output SgTimeRecord to stream.
std::ostream & operator<< (std::ostream &out, SgClockState clockState)
Output SgClockState to stream.
Detailed Description
Time management.
Definition in file SgTimeRecord.h.
Enumeration Type Documentation
enum SgClockState
Clock states.
Enumerator:
SG_CLOCK_OFF
The clock is turned off; no time is counted for either player.
SG_CLOCK_RUNNING
The time is running for one of the players.
SG_CLOCK_SUSPENDED
The running clock was turned off by the computer; some actions may automatically cause it to turn back on.
Definition at line 17 of file SgTimeRecord.h.
Function Documentation
std::ostream& operator<< (std::ostream & out, const SgTimeRecord & time)
Output SgTimeRecord to stream.
Definition at line 205 of file SgTimeRecord.cpp.
References SgTimeRecord::ClockIsRunning(), SgTimeRecord::GetClockState(), SgTimeRecord::LoseOnTime(), SgTimeRecord::MovesLeft(), SgTimeRecord::OTNumMoves(), SgTimeRecord::OTPeriod(), SgTimeRecord::Overhead(), SG_BLACK, SG_WHITE, SgTimeRecord::TimeLeft(), and SgTimeRecord::UseOvertime().
std::ostream& operator<< (std::ostream & out, SgClockState clockState)
Output SgClockState to stream.
Definition at line 221 of file SgTimeRecord.cpp.
References SG_ASSERT, SG_CLOCK_OFF, SG_CLOCK_RUNNING, and SG_CLOCK_SUSPENDED.
Sun Mar 13 2011 Doxygen 1.7.1