SmartGame Library: SgTimeRecord.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgTimeRecord.cpp File Reference
See SgTimeRecord.h.
#include "SgSystem.h"
#include "SgTimeRecord.h"
#include <iomanip>
#include <limits>
#include <sstream>
#include "SgDebug.h"
#include "SgNode.h"
#include "SgProp.h"
#include "SgTime.h"
#include "SgWrite.h"
Functions
ostream & operator<< (ostream &out, const SgTimeRecord &time)
Output SgTimeRecord to stream.
ostream & operator<< (ostream &out, SgClockState clockState)
Output SgClockState to stream.
Detailed Description
See SgTimeRecord.h.
Definition in file SgTimeRecord.cpp.
Function Documentation
std::ostream & operator<< (ostream & out, const SgTimeRecord & time)
Output SgTimeRecord to stream.
Definition at line 205 of file SgTimeRecord.cpp.
References SgTimeRecord::ClockIsRunning(), SgTimeRecord::GetClockState(), SgTimeRecord::LoseOnTime(), SgTimeRecord::MovesLeft(), SgTimeRecord::OTNumMoves(), SgTimeRecord::OTPeriod(), SgTimeRecord::Overhead(), SG_BLACK, SG_WHITE, SgTimeRecord::TimeLeft(), and SgTimeRecord::UseOvertime().
ostream& operator<< (std::ostream & out, SgClockState clockState)
Output SgClockState to stream.
Definition at line 221 of file SgTimeRecord.cpp.
References SG_ASSERT, SG_CLOCK_OFF, SG_CLOCK_RUNNING, and SG_CLOCK_SUSPENDED.
Sun Mar 13 2011 Doxygen 1.7.1