SmartGame Library: SgUtil.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgUtil.cpp File Reference
See SgUtil.h.
#include "SgSystem.h"
#include <iostream>
#include "SgBlackWhite.h"
#include "SgUtil.h"
Functions
std::ostream & operator<< (std::ostream &stream, const SgBalancer &balancer)
Detailed Description
See SgUtil.h.
Definition in file SgUtil.cpp.
Function Documentation
std::ostream& operator<< (std::ostream & stream, const SgBalancer & balancer)
Definition at line 12 of file SgUtil.cpp.
References SgBalancer::Balance(), SgBalancer::Margin(), SgBalancer::NuCalls(), SgBalancer::NuPlayed(), SgBalancer::NuRejected(), SG_BLACK, and SG_WHITE.
Sun Mar 13 2011 Doxygen 1.7.1