SmartGame Library: SgUtil.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgUtil.h File Reference
Small utility functions.
#include <iostream>
#include "SgBlackWhite.h"
#include "SgBWArray.h"
Classes
class SgBalancer
Utility class to assure balance between black and white plays.
Namespaces
namespace SgUtil
Functions
template<class T >
void SgUtil::ForceInRange (const T &min, T *p, const T &max)
template<class T >
bool SgUtil::InRange (const T &i, const T &from, const T &to)
template<class T >
void SgUtil::LowerLimit (T &x, const T &limit)
template<class T >
void SgUtil::UpperLimit (T &x, const T &limit)
std::ostream & operator<< (std::ostream &stream, const SgBalancer &balancer)
Detailed Description
Small utility functions.
Definition in file SgUtil.h.
Function Documentation
std::ostream& operator<< (std::ostream & stream, const SgBalancer & balancer)
Definition at line 12 of file SgUtil.cpp.
References SgBalancer::Balance(), SgBalancer::Margin(), SgBalancer::NuCalls(), SgBalancer::NuPlayed(), SgBalancer::NuRejected(), SG_BLACK, and SG_WHITE.
Sun Mar 13 2011 Doxygen 1.7.1