SmartGame Library: SgWrite.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgWrite.cpp File Reference
See SgWrite.h.
#include "SgSystem.h"
#include "SgWrite.h"
#include <cstdio>
#include <iostream>
#include <iomanip>
#include <sstream>
#include "SgVector.h"
Functions
ostream & operator<< (ostream &out, const SgWriteLabel &w)
ostream & operator<< (ostream &out, const SgWriteLine &w)
ostream & operator<< (ostream &out, const SgWriteMove &w)
ostream & operator<< (ostream &out, const SgWritePointList &write)
ostream & operator<< (ostream &out, const SgWriteBoolean &w)
ostream & operator<< (ostream &out, const SgWriteBoolAsInt &write)
Detailed Description
See SgWrite.h.
Definition in file SgWrite.cpp.
Function Documentation
ostream& operator<< (std::ostream & out, const SgWriteLabel & w)
Definition at line 19 of file SgWrite.cpp.
References SgWriteLabel::m_label.
std::ostream & operator<< (ostream & out, const SgWriteBoolAsInt & write)
Definition at line 124 of file SgWrite.cpp.
References SgWriteBoolAsInt::Write().
ostream& operator<< (std::ostream & out, const SgWriteBoolean & w)
Definition at line 103 of file SgWrite.cpp.
References SgWriteBoolean::m_value.
std::ostream & operator<< (ostream & out, const SgWritePointList & write)
Definition at line 98 of file SgWrite.cpp.
References SgWritePointList::Write().
ostream& operator<< (std::ostream & out, const SgWriteMove & w)
Definition at line 43 of file SgWrite.cpp.
References SgWriteMove::m_color, SgWriteMove::m_point, and SgBW().
ostream& operator<< (std::ostream & out, const SgWriteLine & w)
Definition at line 26 of file SgWrite.cpp.
References SG_UNUSED().
Sun Mar 13 2011 Doxygen 1.7.1