SmartGame Library: SgWrite.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgWrite.h File Reference
Utility write functions for SmartGo data types.
#include <iomanip>
#include <iosfwd>
#include <sstream>
#include <string>
#include <vector>
#include "SgArrayList.h"
#include "SgBoardColor.h"
#include "SgPoint.h"
#include "SgVector.h"
Classes
class SgWriteLabel
Write left aligned text with a minimum width of 15 characters.
class SgWritePointList
Write all points in list.
class SgWriteSPointList< SIZE >
Output a SgSList with SgPoint elements to a stream.
class SgWriteMove
Write player color and move for games in which a move is a SgPoint.
class SgWriteLine
Write line of dashes.
class SgWriteBoolean
Only writes "not" if value is false.
class SgWriteBoolAsInt
Writes boolean as 0/1.
Functions
std::ostream & operator<< (std::ostream &out, const SgWritePointList &write)
template<int SIZE>
std::ostream & operator<< (std::ostream &out, const SgWriteSPointList< SIZE > &write)
std::ostream & operator<< (std::ostream &out, const SgWriteBoolAsInt &write)
Detailed Description
Utility write functions for SmartGo data types.
Todo:
Write functions logically belong to the files of the classes they are outputting; should be moved.
Definition in file SgWrite.h.
Function Documentation
std::ostream& operator<< (std::ostream & out, const SgWritePointList & write)
Definition at line 98 of file SgWrite.cpp.
References SgWritePointList::Write().
std::ostream& operator<< (std::ostream & out, const SgWriteBoolAsInt & write)
Definition at line 124 of file SgWrite.cpp.
References SgWriteBoolAsInt::Write().
template<int SIZE> std::ostream & operator<< (std::ostream & out, const SgWriteSPointList< SIZE > & write)
Definition at line 112 of file SgWrite.h.
References SgWriteSPointList< SIZE >::Write().
Sun Mar 13 2011 Doxygen 1.7.1