SmartGame Library: SgBoardConst::BoardConstImpl Struct Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SgBoardConst::BoardConstImpl Struct Reference
Public Member Functions
BoardConstImpl (SgGrid size)
Public Attributes
SgGrid m_size
Size.
int m_firstBoardPoint
int m_lastBoardPoint
SgPointArray< SgGrid > m_gridToLine
SgPointArray< SgGrid > m_gridToPos
SgPoint m_neighbors [SG_MAXPOINT][5]
See SgBoardConst::Neighbors().
SgPointArray< int > m_up
SgPointSet m_corners
SgPointSet m_edges
SgPointSet m_centers
SgPointSet m_sideExtensions
SgPoint m_cornerIter [4+1]
SgPointSet m_line [(SG_MAX_SIZE/2)+1]
SgPoint * m_lineIterAddress [(SG_MAX_SIZE/2)+1]
SgPoint m_boardIter [SG_MAX_ONBOARD+1]
SgPoint * m_boardIterEnd
SgPoint m_lineIter [SG_MAX_SIZE *SG_MAX_SIZE+(SG_MAX_SIZE/2)+1]
int m_side [2][2 *(SG_NS+SG_WE)+1]
Detailed Description
Definition at line 103 of file SgBoardConst.h.
Constructor & Destructor Documentation
SgBoardConst::BoardConstImpl::BoardConstImpl (SgGrid size)
Definition at line 18 of file SgBoardConst.cpp.
References SgPointSet::Exclude(), SgArray< T, SIZE >::Fill(), SgPointSet::Include(), m_boardIter, m_boardIterEnd, m_centers, m_cornerIter, m_corners, m_edges, m_firstBoardPoint, m_gridToLine, m_gridToPos, m_lastBoardPoint, m_line, m_lineIter, m_lineIterAddress, m_neighbors, m_side, m_sideExtensions, m_size, m_up, SgPointUtil::Pt(), SG_ASSERT, SG_ENDPOINT, SG_MAX_SIZE, SG_MAXPOINT, SG_NS, and SG_WE.
Member Data Documentation
SgPoint SgBoardConst::BoardConstImpl::m_boardIter[SG_MAX_ONBOARD+1]
Definition at line 137 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPoint* SgBoardConst::BoardConstImpl::m_boardIterEnd
Definition at line 139 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPointSet SgBoardConst::BoardConstImpl::m_centers
Definition at line 127 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPoint SgBoardConst::BoardConstImpl::m_cornerIter[4+1]
Definition at line 131 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPointSet SgBoardConst::BoardConstImpl::m_corners
Definition at line 123 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPointSet SgBoardConst::BoardConstImpl::m_edges
Definition at line 125 of file SgBoardConst.h.
Referenced by BoardConstImpl().
int SgBoardConst::BoardConstImpl::m_firstBoardPoint
Definition at line 110 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPointArray<SgGrid> SgBoardConst::BoardConstImpl::m_gridToLine
Definition at line 114 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPointArray<SgGrid> SgBoardConst::BoardConstImpl::m_gridToPos
Definition at line 116 of file SgBoardConst.h.
Referenced by BoardConstImpl().
int SgBoardConst::BoardConstImpl::m_lastBoardPoint
Definition at line 112 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPointSet SgBoardConst::BoardConstImpl::m_line[(SG_MAX_SIZE/2)+1]
Definition at line 133 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPoint SgBoardConst::BoardConstImpl::m_lineIter[SG_MAX_SIZE *SG_MAX_SIZE+(SG_MAX_SIZE/2)+1]
Definition at line 141 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPoint* SgBoardConst::BoardConstImpl::m_lineIterAddress[(SG_MAX_SIZE/2)+1]
Definition at line 135 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPoint SgBoardConst::BoardConstImpl::m_neighbors[SG_MAXPOINT][5]
See SgBoardConst::Neighbors().
Definition at line 119 of file SgBoardConst.h.
Referenced by BoardConstImpl().
int SgBoardConst::BoardConstImpl::m_side[2][2 *(SG_NS+SG_WE)+1]
Definition at line 143 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPointSet SgBoardConst::BoardConstImpl::m_sideExtensions
Definition at line 129 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgGrid SgBoardConst::BoardConstImpl::m_size
Size.
Definition at line 108 of file SgBoardConst.h.
Referenced by BoardConstImpl().
SgPointArray<int> SgBoardConst::BoardConstImpl::m_up
Definition at line 121 of file SgBoardConst.h.
Referenced by BoardConstImpl().
The documentation for this struct was generated from the following files:
SgBoardConst.h
SgBoardConst.cpp
Sun Mar 13 2011 Doxygen 1.7.1