SimplePlayers Library: SpInfluenceMoveGenerator Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SpInfluenceMoveGenerator Class Reference
The influence move generator tries to maximize influence.
#include <SpInfluencePlayer.h>
Public Member Functions
SpInfluenceMoveGenerator (const GoBoard &board)
int Evaluate ()
int EvaluateMove (SgPoint p)
Execute move, then evaluate board.
virtual void GenerateMoves (SgEvaluatedMoves &eval, SgBlackWhite toPlay)
Protected Attributes
const GoBoard & m_board
Reference to go board on which to play.
Detailed Description
The influence move generator tries to maximize influence.
Definition at line 15 of file SpInfluencePlayer.h.
Constructor & Destructor Documentation
SpInfluenceMoveGenerator::SpInfluenceMoveGenerator (const GoBoard & board) [explicit]
Definition at line 19 of file SpInfluencePlayer.h.
Member Function Documentation
int SpInfluenceMoveGenerator::Evaluate () [virtual]
Implements Sp1PlyMoveGenerator.
Definition at line 14 of file SpInfluencePlayer.cpp.
References GoInfluence::Influence(), LibertyMinus2(), SpMoveGenerator::m_board, GoBoard::Opponent(), and SgOppBW().
int Sp1PlyMoveGenerator::EvaluateMove (SgPoint p) [virtual, inherited]
Execute move, then evaluate board.
Implements SpMoveGenerator.
Definition at line 35 of file SpMoveGenerator.cpp.
References GoModBoard::Board(), Sp1PlyMoveGenerator::Evaluate(), GoMoveExecutor::IsLegal(), and SpMoveGenerator::m_board.
void SpMoveGenerator::GenerateMoves (SgEvaluatedMoves & eval, SgBlackWhite toPlay) [virtual, inherited]
Reimplemented in SpDumbTacticalMoveGenerator, and SpLadderMoveGenerator.
Definition at line 18 of file SpMoveGenerator.cpp.
References SgEvaluatedMoves::AddMove(), GoModBoard::Board(), SpMoveGenerator::EvaluateMove(), SpMoveGenerator::m_board, SgEvaluatedMoves::Relevant(), and GoBoard::SetToPlay().
Referenced by SpSimplePlayer::GenMove().
Member Data Documentation
const GoBoard& SpMoveGenerator::m_board [protected, inherited]
Reference to go board on which to play.
Definition at line 33 of file SpMoveGenerator.h.
Referenced by SpSafeMoveGenerator::Evaluate(), SpMinLibMoveGenerator::Evaluate(), SpMaxEyeMoveGenerator::Evaluate(), Evaluate(), SpGreedyMoveGenerator::Evaluate(), SpCaptureMoveGenerator::Evaluate(), SpAverageMoveGenerator::Evaluate(), SpStaticMoveGenerator::EvaluateMove(), Sp1PlyMoveGenerator::EvaluateMove(), SpDumbTacticalMoveGenerator::GenerateAttackMoves(), SpDumbTacticalMoveGenerator::GenerateDefendMoves(), SpMoveGenerator::GenerateMoves(), SpLadderMoveGenerator::GenerateMoves(), SpDumbTacticalMoveGenerator::GenerateMoves(), SpMaxEyeMoveGenerator::Heuristic(), SpMinLibMoveGenerator::LibertyMinimum(), SpRandomMoveGenerator::Score(), and SpLibertyMoveGenerator::Score().
The documentation for this class was generated from the following files:
SpInfluencePlayer.h
SpInfluencePlayer.cpp
Sun Mar 13 2011 Doxygen 1.7.1