SimplePlayers Library: SpLibertyMoveGenerator Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SpLibertyMoveGenerator Class Reference
Tries to capture and escape with low liberty stones Blocks with few liberties are very important to this player.
#include <SpLibertyPlayer.h>
Public Member Functions
SpLibertyMoveGenerator (const GoBoard &board)
int Score (SgPoint p)
int EvaluateMove (SgPoint p)
Static move evaluation.
virtual void GenerateMoves (SgEvaluatedMoves &eval, SgBlackWhite toPlay)
Protected Attributes
const GoBoard & m_board
Reference to go board on which to play.
Detailed Description
Tries to capture and escape with low liberty stones Blocks with few liberties are very important to this player.
Definition at line 16 of file SpLibertyPlayer.h.
Constructor & Destructor Documentation
SpLibertyMoveGenerator::SpLibertyMoveGenerator (const GoBoard & board)
Definition at line 20 of file SpLibertyPlayer.h.
Member Function Documentation
int SpStaticMoveGenerator::EvaluateMove (SgPoint p) [virtual, inherited]
Static move evaluation.
Implements SpMoveGenerator.
Definition at line 46 of file SpMoveGenerator.cpp.
References GoBoard::IsLegal(), SpMoveGenerator::m_board, and SpStaticMoveGenerator::Score().
void SpMoveGenerator::GenerateMoves (SgEvaluatedMoves & eval, SgBlackWhite toPlay) [virtual, inherited]
Reimplemented in SpDumbTacticalMoveGenerator, and SpLadderMoveGenerator.
Definition at line 18 of file SpMoveGenerator.cpp.
References SgEvaluatedMoves::AddMove(), GoModBoard::Board(), SpMoveGenerator::EvaluateMove(), SpMoveGenerator::m_board, SgEvaluatedMoves::Relevant(), and GoBoard::SetToPlay().
Referenced by SpSimplePlayer::GenMove().
int SpLibertyMoveGenerator::Score (SgPoint p) [virtual]
Implements SpStaticMoveGenerator.
Definition at line 17 of file SpLibertyPlayer.cpp.
References GoBoard::AllEmpty(), SgPointSet::Border(), ExpandToBlocks(), SgPointSet::Include(), SpMoveGenerator::m_board, MoveLegalAndNotAtari(), GoBoard::NumEmptyNeighbors(), GoBoard::Occupied(), and GoBoard::Size().
Member Data Documentation
const GoBoard& SpMoveGenerator::m_board [protected, inherited]
Reference to go board on which to play.
Definition at line 33 of file SpMoveGenerator.h.
Referenced by SpSafeMoveGenerator::Evaluate(), SpMinLibMoveGenerator::Evaluate(), SpMaxEyeMoveGenerator::Evaluate(), SpInfluenceMoveGenerator::Evaluate(), SpGreedyMoveGenerator::Evaluate(), SpCaptureMoveGenerator::Evaluate(), SpAverageMoveGenerator::Evaluate(), SpStaticMoveGenerator::EvaluateMove(), Sp1PlyMoveGenerator::EvaluateMove(), SpDumbTacticalMoveGenerator::GenerateAttackMoves(), SpDumbTacticalMoveGenerator::GenerateDefendMoves(), SpMoveGenerator::GenerateMoves(), SpLadderMoveGenerator::GenerateMoves(), SpDumbTacticalMoveGenerator::GenerateMoves(), SpMaxEyeMoveGenerator::Heuristic(), SpMinLibMoveGenerator::LibertyMinimum(), SpRandomMoveGenerator::Score(), and Score().
The documentation for this class was generated from the following files:
SpLibertyPlayer.h
SpLibertyPlayer.cpp
Sun Mar 13 2011 Doxygen 1.7.1