SimplePlayers Library: SpAveragePlayer Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SpAveragePlayer Class Reference
Simple player using SpAverageMoveGenerator.
#include <SpAveragePlayer.h>
Public Member Functions
SpAveragePlayer (const GoBoard &board)
std::string Name () const
bool UseFilter () const
Don't play on safe points.
SgPoint GenMove (const SgTimeRecord &time, SgBlackWhite toPlay)
virtual int MoveValue (SgPoint p)
GoBoard & Board ()
const GoBoard & Board () const
SgNode * CurrentNode () const
void ClearSearchTraces ()
SgNode * TransferSearchTraces ()
virtual void OnGameFinished ()
virtual void OnNewGame ()
virtual void Ponder ()
int Variant () const
void SetVariant (int variant)
void SetSubscriber (GoBoard &subscriber)
void UpdateSubscriber ()
Protected Member Functions
virtual void OnBoardChange ()
virtual void PrePlay (GoPlayerMove move)
virtual void OnPlay (GoPlayerMove move)
virtual void PreUndo ()
virtual void OnUndo ()
Protected Attributes
SgNode * m_currentNode
Detailed Description
Simple player using SpAverageMoveGenerator.
Definition at line 32 of file SpAveragePlayer.h.
Constructor & Destructor Documentation
SpAveragePlayer::SpAveragePlayer (const GoBoard & board)
Definition at line 36 of file SpAveragePlayer.h.
Member Function Documentation
SgPoint SpSimplePlayer::GenMove (const SgTimeRecord & time, SgBlackWhite toPlay) [virtual, inherited]
Implements GoPlayer.
Definition at line 61 of file SpSimplePlayer.cpp.
References SgEvaluatedMovesArray::BestMove(), GoPlayer::Board(), SpMoveGenerator::GenerateMoves(), SpUtil::GetRelevantMoves(), SpSimplePlayer::m_generator, SpSimplePlayer::m_randomGenerator, SG_PASS, SG_UNUSED(), and SpSimplePlayer::UseFilter().
int SpSimplePlayer::MoveValue (SgPoint p) [virtual, inherited]
Reimplemented from GoPlayer.
Definition at line 43 of file SpSimplePlayer.cpp.
References GoBoard::AllEmpty(), GoPlayer::Board(), SpMoveGenerator::EvaluateMove(), GoSafetySolver::FindSafePoints(), SpSimplePlayer::m_generator, SG_BLACK, SG_WHITE, and SpSimplePlayer::UseFilter().
std::string SpAveragePlayer::Name () const [virtual]
Reimplemented from GoPlayer.
Definition at line 40 of file SpAveragePlayer.h.
bool SpAveragePlayer::UseFilter () const [virtual]
Don't play on safe points.
Reimplemented from SpSimplePlayer.
Definition at line 45 of file SpAveragePlayer.h.
The documentation for this class was generated from the following file:
SpAveragePlayer.h
Sun Mar 13 2011 Doxygen 1.7.1