SimplePlayers Library: Sp1PlyMoveGenerator Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
Sp1PlyMoveGenerator Class Reference
Evaluates move by executing it, then evaluating the board.
#include <SpMoveGenerator.h>
Public Member Functions
Sp1PlyMoveGenerator (const GoBoard &board)
virtual int Evaluate ()=0
int EvaluateMove (SgPoint p)
Execute move, then evaluate board.
virtual void GenerateMoves (SgEvaluatedMoves &eval, SgBlackWhite toPlay)
Protected Attributes
const GoBoard & m_board
Reference to go board on which to play.
Detailed Description
Evaluates move by executing it, then evaluating the board.
Definition at line 58 of file SpMoveGenerator.h.
Constructor & Destructor Documentation
Sp1PlyMoveGenerator::Sp1PlyMoveGenerator (const GoBoard & board) [explicit]
Definition at line 62 of file SpMoveGenerator.h.
Member Function Documentation
virtual int Sp1PlyMoveGenerator::Evaluate () [pure virtual]
Implemented in SpAverageMoveGenerator, SpCaptureMoveGenerator, SpGreedyMoveGenerator, SpInfluenceMoveGenerator, SpMaxEyeMoveGenerator, SpMinLibMoveGenerator, and SpSafeMoveGenerator.
Referenced by EvaluateMove().
int Sp1PlyMoveGenerator::EvaluateMove (SgPoint p) [virtual]
Execute move, then evaluate board.
Implements SpMoveGenerator.
Definition at line 35 of file SpMoveGenerator.cpp.
References GoModBoard::Board(), Evaluate(), GoMoveExecutor::IsLegal(), and SpMoveGenerator::m_board.
void SpMoveGenerator::GenerateMoves (SgEvaluatedMoves & eval, SgBlackWhite toPlay) [virtual, inherited]
Reimplemented in SpDumbTacticalMoveGenerator, and SpLadderMoveGenerator.
Definition at line 18 of file SpMoveGenerator.cpp.
References SgEvaluatedMoves::AddMove(), GoModBoard::Board(), SpMoveGenerator::EvaluateMove(), SpMoveGenerator::m_board, SgEvaluatedMoves::Relevant(), and GoBoard::SetToPlay().
Referenced by SpSimplePlayer::GenMove().
Member Data Documentation
const GoBoard& SpMoveGenerator::m_board [protected, inherited]
Reference to go board on which to play.
Definition at line 33 of file SpMoveGenerator.h.
Referenced by SpSafeMoveGenerator::Evaluate(), SpMinLibMoveGenerator::Evaluate(), SpMaxEyeMoveGenerator::Evaluate(), SpInfluenceMoveGenerator::Evaluate(), SpGreedyMoveGenerator::Evaluate(), SpCaptureMoveGenerator::Evaluate(), SpAverageMoveGenerator::Evaluate(), SpStaticMoveGenerator::EvaluateMove(), EvaluateMove(), SpDumbTacticalMoveGenerator::GenerateAttackMoves(), SpDumbTacticalMoveGenerator::GenerateDefendMoves(), SpMoveGenerator::GenerateMoves(), SpLadderMoveGenerator::GenerateMoves(), SpDumbTacticalMoveGenerator::GenerateMoves(), SpMaxEyeMoveGenerator::Heuristic(), SpMinLibMoveGenerator::LibertyMinimum(), SpRandomMoveGenerator::Score(), and SpLibertyMoveGenerator::Score().
The documentation for this class was generated from the following files:
SpMoveGenerator.h
SpMoveGenerator.cpp
Sun Mar 13 2011 Doxygen 1.7.1