SimplePlayers Library: SpUtil Namespace Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SpUtil Namespace Reference
Functions
SgPointSet GetRelevantMoves (GoBoard &bd, SgBlackWhite toPlay, bool useFilter)
Get all legal moves.
Function Documentation
SgPointSet SpUtil::GetRelevantMoves (GoBoard & bd, SgBlackWhite toPlay, bool useFilter)
Get all legal moves.
Filters out moves into own safe territory with no opponent stones adjacent if useFilter.
Definition at line 15 of file SpUtil.cpp.
References GoBoard::AllEmpty(), GoRules::CaptureDead(), GoSafetySolver::FindSafePoints(), GoBoard::HasNeighbors(), SgPointSet::Include(), GoBoard::IsLegal(), GoBoard::Rules(), and SgOppBW().
Referenced by SpSimplePlayer::GenMove().
Sun Mar 13 2011 Doxygen 1.7.1