SimplePlayers Library: SpAveragePlayer.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
SpAveragePlayer.cpp File Reference
See SpAveragePlayer.h.
#include "SgSystem.h"
#include "SpAveragePlayer.h"
#include "SgConnCompIterator.h"
Functions
int LibertyAveragex10 (const GoBoard &board, SgBlackWhite color)
Average number of liberties of blocks of color, multiplied by 10.
Detailed Description
See SpAveragePlayer.h.
Definition in file SpAveragePlayer.cpp.
Function Documentation
int LibertyAveragex10 (const GoBoard & board, SgBlackWhite color)
Average number of liberties of blocks of color, multiplied by 10.
Definition at line 13 of file SpAveragePlayer.cpp.
References GoBoard::All(), GoBoard::AllEmpty(), and GoBoard::Size().
Referenced by SpMinLibMoveGenerator::Evaluate(), and SpAverageMoveGenerator::Evaluate().
Sun Mar 13 2011 Doxygen 1.7.1