GoUct Library: GoUctKnowledge Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoUctKnowledge Class Reference
Base knowledge class.
#include <GoUctDefaultPriorKnowledge.h>
Public Member Functions
GoUctKnowledge (const GoBoard &bd)
virtual ~GoUctKnowledge ()
virtual void ProcessPosition (std::vector< SgUctMoveInfo > &moves)=0
Protected Member Functions
void Add (SgPoint p, SgUctValue value, SgUctValue count)
void Initialize (SgPoint p, SgUctValue value, SgUctValue count)
void ClearValues ()
void TransferValues (std::vector< SgUctMoveInfo > &outmoves) const
Protected Attributes
const GoBoard & m_bd
SgArray< SgStatisticsBase
< SgUctValue, SgUctValue >
, SG_PASS+1 > m_values
Detailed Description
Base knowledge class.
Definition at line 14 of file GoUctDefaultPriorKnowledge.h.
Constructor & Destructor Documentation
GoUctKnowledge::GoUctKnowledge (const GoBoard & bd)
Definition at line 40 of file GoUctDefaultPriorKnowledge.cpp.
GoUctKnowledge::~GoUctKnowledge () [virtual]
Definition at line 45 of file GoUctDefaultPriorKnowledge.cpp.
Member Function Documentation
void GoUctKnowledge::Add (SgPoint p, SgUctValue value, SgUctValue count) [protected]
Definition at line 49 of file GoUctDefaultPriorKnowledge.cpp.
References m_values.
Referenced by GoUctDefaultPriorKnowledge::AddLocalityBonus().
void GoUctKnowledge::ClearValues () [protected]
Definition at line 59 of file GoUctDefaultPriorKnowledge.cpp.
References m_values, and SG_PASS.
void GoUctKnowledge::Initialize (SgPoint p, SgUctValue value, SgUctValue count) [protected]
Definition at line 54 of file GoUctDefaultPriorKnowledge.cpp.
References m_values.
Referenced by GoUctDefaultPriorKnowledge::ProcessPosition().
virtual void GoUctKnowledge::ProcessPosition (std::vector< SgUctMoveInfo > & moves) [pure virtual]
Implemented in GoUctDefaultPriorKnowledge.
void GoUctKnowledge::TransferValues (std::vector< SgUctMoveInfo > & outmoves) const [protected]
Definition at line 65 of file GoUctDefaultPriorKnowledge.cpp.
References SgUctSearch::InverseEstimate(), and m_values.
Referenced by GoUctDefaultPriorKnowledge::ProcessPosition().
Member Data Documentation
const GoBoard& GoUctKnowledge::m_bd [protected]
Definition at line 24 of file GoUctDefaultPriorKnowledge.h.
Referenced by GoUctDefaultPriorKnowledge::AddLocalityBonus(), GoUctDefaultPriorKnowledge::FindGlobalPatternAndAtariMoves(), and GoUctDefaultPriorKnowledge::ProcessPosition().
SgArray<SgStatisticsBase<SgUctValue,SgUctValue>,SG_PASS+1> GoUctKnowledge::m_values [protected]
Definition at line 26 of file GoUctDefaultPriorKnowledge.h.
Referenced by Add(), ClearValues(), Initialize(), GoUctDefaultPriorKnowledge::ProcessPosition(), and TransferValues().
The documentation for this class was generated from the following files:
GoUctDefaultPriorKnowledge.h
GoUctDefaultPriorKnowledge.cpp
Sun Mar 13 2011 Doxygen 1.7.1