GoUct Library: GoUctBookBuilder< PLAYER >::Worker Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoUctBookBuilder< PLAYER >::Worker Class Reference
Copyable worker.
Public Member Functions
Worker (std::size_t id, PLAYER &player)
float operator() (const SgMove &move)
Private Attributes
std::size_t m_id
PLAYER * m_player
Detailed Description
template<class PLAYER>
class GoUctBookBuilder< PLAYER >::Worker
Copyable worker.
Definition at line 115 of file GoUctBookBuilder.h.
Constructor & Destructor Documentation
template<class PLAYER > GoUctBookBuilder< PLAYER >::Worker::Worker (std::size_t id, PLAYER & player)
Definition at line 288 of file GoUctBookBuilder.h.
Member Function Documentation
template<class PLAYER > float GoUctBookBuilder< PLAYER >::Worker::operator() (const SgMove & move)
Definition at line 296 of file GoUctBookBuilder.h.
References GoUctBookBuilder< PLAYER >::Worker::m_player, SgUctNode::Mean(), SgUctTree::Root(), and SgUctSearch::Tree().
Member Data Documentation
template<class PLAYER > std::size_t GoUctBookBuilder< PLAYER >::Worker::m_id [private]
Definition at line 123 of file GoUctBookBuilder.h.
template<class PLAYER > PLAYER* GoUctBookBuilder< PLAYER >::Worker::m_player [private]
Definition at line 125 of file GoUctBookBuilder.h.
Referenced by GoUctBookBuilder< PLAYER >::Worker::operator()().
The documentation for this class was generated from the following file:
GoUctBookBuilder.h
Sun Mar 13 2011 Doxygen 1.7.1