GoUct Library: GoUctPlayoutPolicy< BOARD >::CaptureGenerator Class Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoUctPlayoutPolicy< BOARD >::CaptureGenerator Class Reference
Incrementally keeps track of blocks in atari.
Public Member Functions
CaptureGenerator (const BOARD &bd)
void StartPlayout ()
void OnPlay ()
void Generate (GoPointList &moves)
Generate capture moves.
Private Attributes
const BOARD & m_bd
std::vector< SgPoint > m_candidates
Anchor stones of blocks that need to be checked for atari.
Detailed Description
template<class BOARD>
class GoUctPlayoutPolicy< BOARD >::CaptureGenerator
Incrementally keeps track of blocks in atari.
Definition at line 167 of file GoUctPlayoutPolicy.h.
Constructor & Destructor Documentation
template<class BOARD> GoUctPlayoutPolicy< BOARD >::CaptureGenerator::CaptureGenerator (const BOARD & bd)
Definition at line 278 of file GoUctPlayoutPolicy.h.
References GO_MAX_NUM_MOVES, and GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_candidates.
Member Function Documentation
template<class BOARD > void GoUctPlayoutPolicy< BOARD >::CaptureGenerator::Generate (GoPointList & moves)
Generate capture moves.
Parameters:
[out] moves The resulting list of capture moves. The passed in list is expected to be empty.
Definition at line 317 of file GoUctPlayoutPolicy.h.
References SgArrayList< T, SIZE >::IsEmpty(), GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_bd, GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_candidates, SgArrayList< T, SIZE >::PushBack(), and SG_ASSERT.
Referenced by GoUctPlayoutPolicy< BOARD >::GenerateMove().
template<class BOARD > void GoUctPlayoutPolicy< BOARD >::CaptureGenerator::OnPlay ()
Definition at line 297 of file GoUctPlayoutPolicy.h.
References GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_bd, GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_candidates, SG_NS, SG_NULLMOVE, SG_PASS, and SG_WE.
Referenced by GoUctPlayoutPolicy< BOARD >::OnPlay().
template<class BOARD > void GoUctPlayoutPolicy< BOARD >::CaptureGenerator::StartPlayout ()
Definition at line 285 of file GoUctPlayoutPolicy.h.
References GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_bd, and GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_candidates.
Referenced by GoUctPlayoutPolicy< BOARD >::StartPlayout().
Member Data Documentation
template<class BOARD> const BOARD& GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_bd [private]
Definition at line 182 of file GoUctPlayoutPolicy.h.
Referenced by GoUctPlayoutPolicy< BOARD >::CaptureGenerator::Generate(), GoUctPlayoutPolicy< BOARD >::CaptureGenerator::OnPlay(), and GoUctPlayoutPolicy< BOARD >::CaptureGenerator::StartPlayout().
template<class BOARD> std::vector<SgPoint> GoUctPlayoutPolicy< BOARD >::CaptureGenerator::m_candidates [private]
Anchor stones of blocks that need to be checked for atari.
Definition at line 185 of file GoUctPlayoutPolicy.h.
Referenced by GoUctPlayoutPolicy< BOARD >::CaptureGenerator::CaptureGenerator(), GoUctPlayoutPolicy< BOARD >::CaptureGenerator::Generate(), GoUctPlayoutPolicy< BOARD >::CaptureGenerator::OnPlay(), and GoUctPlayoutPolicy< BOARD >::CaptureGenerator::StartPlayout().
The documentation for this class was generated from the following file:
GoUctPlayoutPolicy.h
Sun Mar 13 2011 Doxygen 1.7.1