GoUct Library: GoUctPlayoutPolicy.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoUctPlayoutPolicy.cpp File Reference
#include "SgSystem.h"
#include "GoUctPlayoutPolicy.h"
#include <algorithm>
#include <boost/io/ios_state.hpp>
Functions
const char * GoUctPlayoutPolicyTypeStr (GoUctPlayoutPolicyType type)
Detailed Description
Definition in file GoUctPlayoutPolicy.cpp.
Function Documentation
const char* GoUctPlayoutPolicyTypeStr (GoUctPlayoutPolicyType type)
Definition at line 25 of file GoUctPlayoutPolicy.cpp.
References _GOUCT_NU_DEFAULT_PLAYOUT_TYPE, BOOST_STATIC_ASSERT(), GOUCT_ATARI_CAPTURE, GOUCT_ATARI_DEFEND, GOUCT_CAPTURE, GOUCT_CLUMP_CORRECTION, GOUCT_FILLBOARD, GOUCT_LOWLIB, GOUCT_NAKADE, GOUCT_PASS, GOUCT_PATTERN, GOUCT_RANDOM, and GOUCT_SELFATARI_CORRECTION.
Referenced by GoUctCommands::CmdPolicyMoves(), and GoUctPlayoutPolicyStat::Write().
Sun Mar 13 2011 Doxygen 1.7.1