GoUct Library: GoUctPlayoutPolicy.h File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoUctPlayoutPolicy.h File Reference
#include <iostream>
#include <boost/array.hpp>
#include "GoBoardUtil.h"
#include "GoEyeUtil.h"
#include "GoUctPatterns.h"
#include "GoUctPureRandomGenerator.h"
Classes
class GoUctPlayoutPolicyParam
Parameters for GoUctPlayoutPolicy.
struct GoUctPlayoutPolicyStat
Statistics collected by GoUctPlayoutPolicy.
class GoUctPlayoutPolicy< BOARD >
Default playout policy for usage in GoUctGlobalSearch.
class GoUctPlayoutPolicy< BOARD >::CaptureGenerator
Incrementally keeps track of blocks in atari.
class GoUctPlayoutPolicyFactory< BOARD >
Enumerations
enum GoUctPlayoutPolicyType {
GOUCT_FILLBOARD, GOUCT_NAKADE, GOUCT_ATARI_CAPTURE, GOUCT_ATARI_DEFEND,
GOUCT_LOWLIB, GOUCT_PATTERN, GOUCT_CAPTURE, GOUCT_RANDOM,
GOUCT_SELFATARI_CORRECTION, GOUCT_CLUMP_CORRECTION, GOUCT_PASS, _GOUCT_NU_DEFAULT_PLAYOUT_TYPE
}
Move types used in GoUctPlayoutPolicy.
Functions
const char * GoUctPlayoutPolicyTypeStr (GoUctPlayoutPolicyType type)
Detailed Description
Definition in file GoUctPlayoutPolicy.h.
Enumeration Type Documentation
enum GoUctPlayoutPolicyType
Move types used in GoUctPlayoutPolicy.
Enumerator:
GOUCT_FILLBOARD
GOUCT_NAKADE
GOUCT_ATARI_CAPTURE
GOUCT_ATARI_DEFEND
GOUCT_LOWLIB
GOUCT_PATTERN
GOUCT_CAPTURE
GOUCT_RANDOM
GOUCT_SELFATARI_CORRECTION
GOUCT_CLUMP_CORRECTION
GOUCT_PASS
_GOUCT_NU_DEFAULT_PLAYOUT_TYPE
Definition at line 42 of file GoUctPlayoutPolicy.h.
Function Documentation
const char* GoUctPlayoutPolicyTypeStr (GoUctPlayoutPolicyType type)
Definition at line 25 of file GoUctPlayoutPolicy.cpp.
References _GOUCT_NU_DEFAULT_PLAYOUT_TYPE, BOOST_STATIC_ASSERT(), GOUCT_ATARI_CAPTURE, GOUCT_ATARI_DEFEND, GOUCT_CAPTURE, GOUCT_CLUMP_CORRECTION, GOUCT_FILLBOARD, GOUCT_LOWLIB, GOUCT_NAKADE, GOUCT_PASS, GOUCT_PATTERN, GOUCT_RANDOM, and GOUCT_SELFATARI_CORRECTION.
Referenced by GoUctCommands::CmdPolicyMoves(), and GoUctPlayoutPolicyStat::Write().
Sun Mar 13 2011 Doxygen 1.7.1