GoUct Library: GoUctDefaultRootFilter.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoUctDefaultRootFilter.cpp File Reference
See GoUctDefaultRootFilter.h.
#include "SgSystem.h"
#include "GoUctDefaultRootFilter.h"
#include "GoBensonSolver.h"
#include "GoBoard.h"
#include "GoBoardUtil.h"
#include "GoModBoard.h"
#include "GoSafetySolver.h"
#include "SgWrite.h"
Functions
bool IsEmptyEdge (const GoBoard &bd, SgPoint p)
Return true, if point is on edge line and no stone is within a Manhattan distance of 4.
Detailed Description
See GoUctDefaultRootFilter.h.
Definition in file GoUctDefaultRootFilter.cpp.
Function Documentation
bool IsEmptyEdge (const GoBoard & bd, SgPoint p)
Return true, if point is on edge line and no stone is within a Manhattan distance of 4.
Definition at line 22 of file GoUctDefaultRootFilter.cpp.
References SgPointUtil::Col(), GoBoard::Occupied(), SgPointUtil::Pt(), SgPointUtil::Row(), and GoBoard::Size().
Referenced by GoUctDefaultRootFilter::Get().
Sun Mar 13 2011 Doxygen 1.7.1