GoUct Library: GoUctEstimatorStat Namespace Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoUctEstimatorStat Namespace Reference
Functions
void Compute (GoUctSearch &search, std::size_t trueValueMaxGames, std::size_t maxGames, std::size_t stepSize, const std::string &fileName)
Get statistics for estimators.
Function Documentation
void GoUctEstimatorStat::Compute (GoUctSearch & search, std::size_t trueValueMaxGames, std::size_t maxGames, std::size_t stepSize, const std::string & fileName)
Get statistics for estimators.
First plays each move and performs a search with a large number of games to estimate the true value of the move. Then performs a search at the root node and saves a sample of the values and counts after each game in the search.
Parameters:
search
trueValueMaxGames Number of games to use for the search to determine the true value
maxGames Maximum number of games for actual search.
stepSize Interval of games played to save the values.
fileName File to append the resulting samples to
Definition at line 20 of file GoUctEstimatorStat.cpp.
References GoUctSearch::Board(), SgUctSearch::EndSearch(), SgUctTreeUtil::FindChildWithMove(), SgUctSearch::GenerateAllMoves(), SgUctNode::HasMean(), SgUctNode::HasRaveValue(), SgUctSearch::InverseEstimate(), SgUctNode::Mean(), SgUctNode::MoveCount(), SgUctSearch::MpiSynchronizer(), SgUctSearch::PlayGame(), SgUctNode::RaveCount(), SgUctNode::RaveValue(), SgUctTree::Root(), SgUctSearch::Search(), SgUctSearch::StartSearch(), and SgUctSearch::Tree().
Referenced by GoUctCommands::CmdEstimatorStat().
Sun Mar 13 2011 Doxygen 1.7.1