GoUct Library: GoUctPlayer< SEARCH, THREAD >::Statistics Struct Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
GoUctPlayer< SEARCH, THREAD >::Statistics Struct Reference
Statistics collected by GoUctPlayer.
#include <GoUctPlayer.h>
Public Member Functions
Statistics ()
void Clear ()
void Write (std::ostream &out) const
Write in human readable format.
Public Attributes
std::size_t m_nuGenMove
SgStatisticsExt< float,
std::size_t > m_reuse
SgStatisticsExt< double,
std::size_t > m_gamesPerSecond
Detailed Description
template<class SEARCH, class THREAD>
struct GoUctPlayer< SEARCH, THREAD >::Statistics
Statistics collected by GoUctPlayer.
Definition at line 60 of file GoUctPlayer.h.
Constructor & Destructor Documentation
template<class SEARCH , class THREAD > GoUctPlayer< SEARCH, THREAD >::Statistics::Statistics ()
Definition at line 502 of file GoUctPlayer.h.
References GoUctPlayer< SEARCH, THREAD >::Statistics::Clear().
Member Function Documentation
template<class SEARCH , class THREAD > void GoUctPlayer< SEARCH, THREAD >::Statistics::Clear ()
Definition at line 508 of file GoUctPlayer.h.
References SgStatisticsExt< VALUE, COUNT >::Clear(), GoUctPlayer< SEARCH, THREAD >::Statistics::m_gamesPerSecond, GoUctPlayer< SEARCH, THREAD >::Statistics::m_nuGenMove, and GoUctPlayer< SEARCH, THREAD >::Statistics::m_reuse.
Referenced by GoUctPlayer< SEARCH, THREAD >::ClearStatistics(), and GoUctPlayer< SEARCH, THREAD >::Statistics::Statistics().
template<class SEARCH , class THREAD > void GoUctPlayer< SEARCH, THREAD >::Statistics::Write (std::ostream & out) const
Write in human readable format.
Definition at line 528 of file GoUctPlayer.h.
References GoUctPlayer< SEARCH, THREAD >::Statistics::m_gamesPerSecond, GoUctPlayer< SEARCH, THREAD >::Statistics::m_nuGenMove, GoUctPlayer< SEARCH, THREAD >::Statistics::m_reuse, and SgStatisticsExt< VALUE, COUNT >::Write().
Member Data Documentation
template<class SEARCH, class THREAD> SgStatisticsExt<double,std::size_t> GoUctPlayer< SEARCH, THREAD >::Statistics::m_gamesPerSecond
Definition at line 66 of file GoUctPlayer.h.
Referenced by GoUctPlayer< SEARCH, THREAD >::Statistics::Clear(), GoUctPlayer< SEARCH, THREAD >::GenMove(), and GoUctPlayer< SEARCH, THREAD >::Statistics::Write().
template<class SEARCH, class THREAD> std::size_t GoUctPlayer< SEARCH, THREAD >::Statistics::m_nuGenMove
Definition at line 62 of file GoUctPlayer.h.
Referenced by GoUctPlayer< SEARCH, THREAD >::Statistics::Clear(), GoUctPlayer< SEARCH, THREAD >::GenMove(), and GoUctPlayer< SEARCH, THREAD >::Statistics::Write().
template<class SEARCH, class THREAD> SgStatisticsExt<float,std::size_t> GoUctPlayer< SEARCH, THREAD >::Statistics::m_reuse
Definition at line 64 of file GoUctPlayer.h.
Referenced by GoUctPlayer< SEARCH, THREAD >::Statistics::Clear(), GoUctPlayer< SEARCH, THREAD >::FindInitTree(), and GoUctPlayer< SEARCH, THREAD >::Statistics::Write().
The documentation for this struct was generated from the following file:
GoUctPlayer.h
Sun Mar 13 2011 Doxygen 1.7.1