FuegoTest Application: FuegoTestMain.cpp File Reference
Index Main Namespaces Classes Hierarchy Annotated Files Compound Global Pages
FuegoTestMain.cpp File Reference
Main function for FuegoTest.
#include "SgSystem.h"
#include <iostream>
#include "FuegoTestEngine.h"
#include "GoInit.h"
#include "SgDebug.h"
#include "SgException.h"
#include "SgInit.h"
#include <boost/utility.hpp>
#include <boost/program_options/options_description.hpp>
#include <boost/program_options/cmdline.hpp>
#include <boost/program_options/variables_map.hpp>
#include <boost/program_options/parsers.hpp>
Functions
int main (int argc, char **argv)
Detailed Description
Main function for FuegoTest.
Definition in file FuegoTestMain.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 97 of file FuegoTestMain.cpp.
References GoFini(), GoInit(), GtpFailure::Response(), SgDebug(), SgDebugToNull(), SgFini(), SgInit(), and SgException::what().
Sun Mar 13 2011 Doxygen 1.7.1